### PR TITLE
Let sphinx_rtd_theme version float in conda builds.

### PR DESCRIPTION
**Pull request by anntzer**
Closes https://github.com/rtfd/readthedocs.org/pull/2779#issuecomment-293060398.

### CODE REVIEW

**Comment by humitos** [comment]
Related to #2802. I think we should keep discussing the idea of no pin packages for conda environment at all since `conda` users are more expertise to be able to install by themselves and not block them with pinned versions instead.

**Comment by ericholscher** [comment]
This is now fixed in master. We'll do a deploy later this week or next week with all the pycon changes. Thanks!

**Comment by anntzer** [comment]
Is there any way I can check what is the currently deployed version (well, right now I care whether this patch is included, but I may as well not have to ask every time...)?  Thanks.

**Comment by humitos** [comment]
The deployed version is the branch `rel`

**Comment by anntzer** [comment]
thanks.

**Pull request closed without merging**
