### PR TITLE
Decouple the theme JS from readthedocs.org

### PR DESCRIPTION
**Pull request by davidfischer**
This PR changes the JavaScript injected onto docs pages. It does not include the Read the Docs theme JS if it is already included. After https://github.com/rtfd/sphinx_rtd_theme/pull/614 (presumably sphinx_rtd_theme>0.3.0, **edit >=0.4.0**) it will use the version of JS specific to the theme version. This PR does not rely on the other and can be merged independently.

This PR also documents why certain fixes are necessary and the versions and themes they are necessary on.

Related to but does not rely on https://github.com/rtfd/readthedocs-sphinx-ext/pull/39.

One area for improvement is that we probably don't need to source the entire theme JS (it comes from Bower). Instead, we should separate the theme JS from the JS needed to power the version selector menu.

### CODE REVIEW

**Comment by davidfischer** [comment]
The lint errors are unrelated but there is an eslint error which is relevant. I believe I'll have to ignore it though since I specifically want to not have a [global require](https://eslint.org/docs/rules/global-require). The point of this is to conditionally include JavaScript only for versions of the theme that require it.

**Comment by jessetan** [comment]
Will this also include sphinx_rtd_theme if a different theme is used?

**Comment by davidfischer** [comment]
Yes it will. That is how it currently works before this change as well.

The sphinx_rtd_theme JavaScript is used (even on other themes) to power the version selector menu. This change did not change that.

**Comment by jessetan** [comment]
OK.

> The sphinx_rtd_theme JavaScript is used (even on other themes) to power the version selector menu. This change did not change that.

This feels a bit uncleanly separated, but I don't have a good working suggestion at this time.

**Comment by davidfischer** [comment]
> This feels a bit uncleanly separated, but I don't have a good working suggestion at this time.

I don't disagree. This is also what I highlighted as an area for improvement above when I said:

> One area for improvement is that we probably don't need to source the entire theme JS (it comes from Bower). Instead, we should separate the theme JS from the JS needed to power the version selector menu.

I just view that as a bigger change.

**Comment by ericholscher** [comment]
What's the state of this? Should we be moving forward w/ this now that 0.3.1 is out?

**Comment by davidfischer** [comment]
> What's the state of this? Should we be moving forward w/ this now that 0.3.1 is out?

I believe it should be rolled out.

**Comment by ericholscher** [comment]
This is backwards compat with all versions of the theme right, so we can merge this, and it will work across all versions?

**Comment by davidfischer** [comment]
> This is backwards compat with all versions of the theme right, so we can merge this, and it will work across all versions?

It is supposed to, yes.

**Pull request merged**
