### PR TITLE
Add Sponsors list to footer

### PR DESCRIPTION
**Pull request by davidfischer**
**Edits: 2018-08-01**

This PR got expanded (scope creeped) and now adds a number of sponsors to the footer.

## Brand guidelines & assets

In general, I followed the following the below guidelines except I did desaturate any color if no black and white logo was provided.

* https://buildazure.com/2017/09/25/microsoft-azure-gets-a-new-logo-and-a-manifesto/
* https://www.cloudflare.com/logo/
* https://www.elastic.co/brand
* https://sentry.io/branding/
* https://newrelic.com/about/media-assets
* https://www.pagerduty.com/brand/

## Screenshot

screen shot 2018-08-01 at 10 30 52 am

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks good to me.

**Comment by humitos** [comment]
I like Eric's proposal.

We may want to include together with Cloudflare other services that we use (although, I'm not sure what's the contract we have with them: Azure, Sentry, New Relic, and maybe others that I'm missing here)

**Comment by davidfischer** [comment]
> I think it might be more useful to specify a bit more about what they are providing us

My plan was to link to the upcoming blog post on the subject but I think I like your proposal better.

**Comment by davidfischer** [comment]
I have updated this PR and edited the description. This PR was changed to add a number of sponsors to the footer.

**Comment by humitos** [comment]
I suppose we can merge this PR.

**Pull request merged**
