### PR TITLE
Update/Pull translations from Transifex

### PR DESCRIPTION
**Pull request by humitos**
After reading #4471 and working on #4470 I think we need to improve our flow about _our own_ translations.

The discussion about how to automate this can be tracked under #4471. In the meantime, we should update our app translation manually and that is what this PR does.

```
$ tx pull --force
tx INFO: Pulling translations for resource readthedocs.readthedocs (source: readthedocs/locale/en/LC_MESSAGES/django.po)
tx WARNING:  -> zh_TW: readthedocs/locale/zh_TW/LC_MESSAGES/django.po
tx WARNING:  -> fr: readthedocs/locale/fr/LC_MESSAGES/django.po
tx WARNING:  -> ja: readthedocs/locale/ja/LC_MESSAGES/django.po
tx WARNING:  -> ru: readthedocs/locale/ru/LC_MESSAGES/django.po
tx WARNING:  -> uk: readthedocs/locale/uk/LC_MESSAGES/django.po
tx WARNING:  -> zh_CN: readthedocs/locale/zh_CN/LC_MESSAGES/django.po
tx WARNING:  -> ca: readthedocs/locale/ca/LC_MESSAGES/django.po
tx WARNING:  -> pl: readthedocs/locale/pl/LC_MESSAGES/django.po
tx WARNING:  -> ar: readthedocs/locale/ar/LC_MESSAGES/django.po
tx WARNING:  -> es: readthedocs/locale/es/LC_MESSAGES/django.po
tx WARNING:  -> vi_VN: readthedocs/locale/vi_VN/LC_MESSAGES/django.po
tx WARNING:  -> gl: readthedocs/locale/gl/LC_MESSAGES/django.po
tx WARNING:  -> pt_BR: readthedocs/locale/pt_BR/LC_MESSAGES/django.po
tx WARNING:  -> it: readthedocs/locale/it/LC_MESSAGES/django.po
tx WARNING:  -> nb: readthedocs/locale/nb/LC_MESSAGES/django.po
tx WARNING:  -> de: readthedocs/locale/de/LC_MESSAGES/django.po
tx WARNING:  -> sk: readthedocs/locale/sk/LC_MESSAGES/django.po
tx WARNING:  -> eu: readthedocs/locale/eu/LC_MESSAGES/django.po
tx INFO: Done.

$ dj makemessages --all
processing locale de
processing locale vi_VN
processing locale fr
processing locale ru
processing locale sk
processing locale pl
processing locale gl
processing locale pt_BR
processing locale uk
processing locale eu
processing locale es
processing locale ca
processing locale nb
processing locale ja
processing locale en
processing locale ar
processing locale zh_TW
processing locale it
processing locale zh_CN
```

I suppose that I should run this command also, to update our strings under Transifex:

```
$ tx push --source
```

Although, before doing this I want to be sure of this and I may need extra permissions that allow me to do this. @ericholscher @agjohnson, is this command correct?

### CODE REVIEW

**Comment by ericholscher** [comment]
@xrmx would also be useful to have your input here

**Comment by humitos** [comment]
@xrmx you are right.

Question: is there any problem by pulling from Transifex without pushing first? I thought that in by doing that, I'm bringing newer translations from what already exists in Transifex to our application. Of course, new/updated strings from sources are not pulled because they don't exist yet in Transifex.

I want to know if doing this pull without pushing first could break something.

**Comment by humitos** [comment]
@xrmx the function for `docs` does what I was thinking: https://github.com/rtfd/readthedocs.org/blob/master/fabfile.py#L27

1. pull
1. update `.pot` files
1. push

We may need to split as you did for the app translations, but also, we should include the new resources under the `.tx/config` file as I did in #4478. What do you think?

**Comment by humitos** [comment]
@xrmx :+1: to all you said :)

> I think the optimal workflow is to push the source at each merge and pull before each release.

I'm not sure how to make this automatically in each merge, but I think that we could do this easily on each release at least.

Also, there is an issue #4471 that suggests a way to include a checking in the CI.

**Comment by humitos** [comment]
I'm closing this PR since I need permissions to `push` to Transifex first. After that, I will run `pull` and create a new PR.

**Comment by xrmx** [comment]
The push can be automated in travis, and the source may be commited with the pulled translation at release time?

**Comment by ewjoachim** [comment]
For the sake of it, the doc on conditional stages on Travis:
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-stages

And an example integration of django-oscar that pushes to transifex from travis:
https://searchcode.com/file/92738132/transifex.sh

**Pull request closed without merging**
