### PR TITLE
Add eslint rules and fix errors

### LINKED ISSUE #2909: Increase linting rules for JS
#2905 adds JavaScript linting to our linting process. We should be enabling additional configuration pieces in order to make testing actually useful.

@cmc333333 suggested in #2905:

* "array-callback-return": "off",
* "eqeqeq": "off",
* "guard-for-in": "off",
* "no-inner-declarations": "off",
* "no-loop-func": "off",
* "no-mixed-operators": "off",
* "no-undef": "off",
* "no-use-before-define": "off",
* "one-var": "off",

### PR DESCRIPTION
**Pull request by bansalnitish**
This PR Fixes #2909.

I have tested for all the rules mentioned in the issue. I have set the rules to `error` level when there are no false positives otherwise it is set to `warning` level.

There were 106 errors and warnings. Now we have 0 errors and 31 warnings. All these warnings are false positives.

I would also like to suggest to enforce the following rules:

- indent (especially this)
- semi
- space-unary-ops
- space-before-function-paren
- no-unused-vars

### CODE REVIEW

**Comment by davidfischer** [comment]
I changed the title to note that this is ESLint as opposed to PyLint.

**Comment by davidfischer** [comment]
Firstly, thank you for the first time contribution. ✨ 

This looks well thought through and well done and I'm happy to see this make it into `master` and get run on every commit! I was able to run `tox -e eslint` without issue and I see the same warnings and no errors. I think the changes to the `.eslintrc` are reasonable.

I do think your suggestions (especially `indent`) are good ideas. However, there's probably a lot of fixes around those. I don't think those other fixes should go in this PR.

**Comment by bansalnitish** [comment]
> Firstly, thank you for the first time contribution. sparkles
This looks well thought through and well done and I'm happy to see this make it into master and get run on every commit!

Thank you @davidfischer! 

>  However, there's probably a lot of fixes around those. I don't think those other fixes should go in this PR.

Shall I make a separate PR for that?

**Comment by bansalnitish** [comment]
Hi @davidfischer, is there anything else I need to do here?

**Comment by RichardLitt** [comment]
I believe this is just waiting for @ericholscher to merge. :)

**Comment by ericholscher** [comment]
I'll let @davidfischer do the honors!

**Comment by davidfischer** [comment]
I'll plan to merge this in the next hour or so today.

@bansalnitish, sure a separate PR would be great.

**Comment by bansalnitish** [comment]
Sure @davidfischer, I will make a separate PR!

**Comment by davidfischer** [comment]
For indentation, I ideally let's stick to 4 spaces similar to Python. https://eslint.org/docs/rules/indent

**Pull request merged**
