### PR TITLE
Upgrade django filter

### LINKED ISSUE #2490: Broken/unpegged django-filter dependency
## Details

* Project URL: https://github.com/rtfd/readthedocs.org
* Build URL (if applicable): https://travis-ci.org/rtfd/readthedocs.org/builds/173218817

## Expected Result

Whilst trying to run an instance of readthedocs locally, I ran into exceptions identical to those on the referenced CI build. Specifically `TypeError: 'VersionSlugFilter' object is not iterable`. This occurs on a fresh build, following instructions on http://docs.readthedocs.io/en/latest/install.html and attempting to view / build any of the projects imported by `python manage.py loaddata test_data`.

## Actual Result / Workaround

I noticed that in requirements/pip.txt django-filter is not pegged to any specific version or commit. Adding a reference to a recent release commit resolved the issue on my local installation.

`git+https://github.com/alex/django-filter.git@47042b9#egg=django-filter`

### LINKED ISSUE #2495: 'VersionSlugFilter' object is not iterable
## Details

* Project URL: local
* Build URL (if applicable): local
* Read the Docs username (if applicable): local

## Expected Result
Open new project

*A description of what you wanted to happen*
Fresh ReadTheDocs installation 
Try to open exists or new project
## Actual Result
TypeError at /projects/invoicing/
'VersionSlugFilter' object is not iterable
*A description of what actually happened*
In template 
checkouts/readthedocs.org/readthedocs/templates/core/project_details.html, error at line 35

25	    <div class="filter_form">
26	      <form id="filter_form">
27	        {{ filter.form }}
28	        <input type="submit" value="{% trans "Filter" %}">
29	      </form>
30	    </div>
31	  {% endcomment %}
32	
33	    <div class="module-list-wrapper">
34	      <ul>
35	
            
      {% for version in filter|sort_version_aware %}
      

      
36	        <li class="module-item col-span">
37	        {% if version.uploaded or version.built %}
38	          {# Link to the docs #}
39	          <a class="module-item-title" href="{{ version.get_absolute_url }}">
40	            {% blocktrans with version.slug as slug %} {{ slug }} {% endblocktrans %}
41	          {% if request.user in project.users.all %}
42	            <span class="right-menu quiet">{{ version.get_privacy_level_display }}</span>
43	          {% endif %}
44	          </a>
45	        {% else %}

### LINKED ISSUE #2498: Update django-filter to 1.0
## Details

Sorry for deleting the issue template: This is about technical debt :) It may not be immediately critical, but the advice from the author of django-filter is that it's worth it.

django-filter 1.0 has changes that are backwards incompatible. The release notes are here:

http://django-filter.readthedocs.io/en/latest/migration.html

It means, amongst other this, that all where  `Filter` object instances are iterated on, we have to [add the `.qs` method](http://django-filter.readthedocs.io/en/latest/migration.html#queryset-methods-are-no-longer-proxied).

### PR DESCRIPTION
**Pull request by rpkilby**
Hi all, this should (hopefully) resolve all of the django-filter issues, migrating you to the upcoming 1.0 release. 

should fix #2490, fix #2495, fix #2498, supersede/resolve #2499

### CODE REVIEW

**Comment by benjaoming** [comment]
Agreed, RTD maintainers can skip #2499 in this case - or in case they want to wait for the final django-filter 1.0 release, they could leave this PR until the release day.

@rpkilby how ready do you estimate the current django-filter `develop` branch to be? Or when would you guess it's shipping?

**Comment by rpkilby** [comment]
1.0 is pretty much ready for release. Unless any new bugs are found, the only thing left to do is release it to pypi.

**Comment by benjaoming** [comment]
Cool, in that case I think we should wait for 1.0 on PyPi, and then add `django-filters>=1.0,<1.1` to the requirements file to get rid of the old unpinned git dependency.

**Comment by ericholscher** [comment]
I'll hold off on this, and ship it once the 1.0 release is on PyPI.

**Comment by rpkilby** [comment]
Hi @ericholscher - django-filter 1.0.0 has officially been released. I've updated the pip reqs to lock it at 1.0

**Comment by ericholscher** [comment]
Thanks for the update!

**Pull request merged**
