### PR TITLE
Use shallow clone of rel branch when installing

### PR DESCRIPTION
**Pull request by Code0x58**
I am imagining that people who are following this to the letter would benefit from using the _rel_ (release) branch, and that they won't be fussed about the history.

### CODE REVIEW

**Comment by ericholscher** [comment]
The goal of this document is to have people help with development, not deploy it on another instance, so I think having it makes sense.

**Comment by Code0x58** [comment]
It does seem that way which makes this PR a bit pointless, I probably should have twigged that a fair bit earlier on while doing through the documentation; I think I was just going by the page name (installation) and the task I had.

Would documentation on deployment (under an operations section instead of development) be something that would get accepted?

**Comment by ericholscher** [comment]
Sure! We have this section, which is the best place for it: http://docs.readthedocs.io/en/latest/custom_installs/index.html

**Comment by Code0x58** [comment]
Thanks, I'll try adding to that next week!

**Pull request closed without merging**
