### PR TITLE
Update Git on prod

### PR DESCRIPTION
**Pull request by techtonik**
This is required to fix Edit button on annotated tags
https://github.com/rtfd/readthedocs.org/pull/3441 (reverted fix)

### CODE REVIEW

**Comment by ericholscher** [comment]
I wish this is as easy as it was to update git in our production instances. Our builders are currently running 14.04, so "update git in prod" actually means "fully re-deploy an entire stack of servers". We're going to be transitioning away from Rackspace soon, so that upgrade will take place as part of our server migrations.

**Comment by techtonik** [comment]
@ericholscher from https://docs.readthedocs.io/en/latest/development/buildenvironments.html it looks like those builders are Docker images, so changing them to 16.04 should be easy.

**Comment by ericholscher** [comment]
Git is currently run outside of docker in some cases, for reasons :)

**Comment by techtonik** [comment]
@ericholscher are there any security reasons to keep the workflow undocumented? =)

**Comment by ericholscher** [comment]
Just lack of time.

**Comment by stsewd** [comment]
I'm fixing the edit button problem using gitpython on #4052

**Comment by ericholscher** [comment]
Will go ahead and merge this, as I believe our git is upgraded in production.

**Pull request merged**
