### PR TITLE
Add prospector as a pre-commit hook

### PR DESCRIPTION
**Pull request by humitos**
To continue with #3264 , I added `prospector` to the pre-commit hooks

### CODE REVIEW

**Comment by ericholscher** [comment]
Will this delay the actual committing by the prospector run? Could see that being mildly annoying in some cases.

**Comment by humitos** [comment]
Kind of. prospector will be ran only over those files you just changed for the current commit, no the whole project (as it ran by CI). So, it shouldn't be too slow.

On the other hand, each plugin of `pre-commit` can be disabled for a specific commit by:

    SKIP=prospector git commit

and this command will run all of the other plugins but prospector.

BTW, it's still just an idea since I haven't tried too much yet... but I think it could be good to have the same info on your computer instead of waiting for CI to finish.

**Comment by ericholscher** [comment]
Neat, I like that it only applies to changed files.

**Comment by agjohnson** [comment]
Neat! This is a step that should be handled before commits go up anyways, but we'll see how intrusive pre-commit and plugins become as our linting efforts mature.

Errors look unrelated, merging this.

**Pull request merged**
