### PR TITLE
Mark some BuildEnvironmentError exceptions as Warning and do not log them

### PR DESCRIPTION
**Pull request by humitos**
There are some exceptions risen while building documentation that are considered an ERROR from the Build perspective, but for our application are just a WARNING and shouldn't be logged as ERROR (sent to Sentry).

It's not an ERROR in our application but a WARNING that the user's documentation couldn't be built.

This will help us to find Sentry more useful than it's right now as we are getting close to have logged only things that need human/dev attention.

> NOTE: this is the most important commit https://github.com/rtfd/readthedocs.org/pull/4495/commits/1dd850a4e276b4849f45ebe3eabdc17e61be0cc9, the first one is a minimum refactor and the last one introduces some style changes

Closes: #4109

### CODE REVIEW

**Comment by ericholscher** [comment]
@humitos we just hit our limit again, we should fix the conflict here and ship it.

**Comment by humitos** [comment]
Rebased the branch. Once the tests passed, I will merge it.

**Comment by stsewd** [comment]
This solves https://github.com/rtfd/readthedocs.org/issues/3856? or we still need less logs?

**Comment by humitos** [comment]
I don't think it 100% solves it, but at least reduce the noise.

I'd like to get to the point to anything logged in Sentry requires manual/human attention. Currently, there are still lot of garbage there.

**Pull request merged**
