### PR TITLE
Upgrade theme media to 0.4.2

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by ericholscher** [comment]
Is this still necessary, now that we're not injecting overrides into the theme?

**Comment by davidfischer** [comment]
> Is this still necessary, now that we're not injecting overrides into the theme?

It is not necessary.

**Comment by agjohnson** [comment]
I think projects that haven't been built in a while would still be requesting our override files though. Did we address that yet?

**Comment by davidfischer** [comment]
> I think projects that haven't been built in a while would still be requesting our override files though. Did we address that yet?

Projects that haven't been built with the new theme will still request the files from assets.readthedocs.org. However, they are built with the old theme so they should request the old theme's files. If they were built with the new theme, they will get the new theme's files in their built artifacts.

**Comment by ericholscher** [comment]
👍

**Comment by ericholscher** [comment]
Opened https://github.com/rtfd/sphinx_rtd_theme/pull/684 to remove the instructions to do it.

**Comment by davidfischer** [comment]
I don't think we wanted to merge this.

**Comment by ericholscher** [comment]
Ha yea, I hit the wrong button :(

**Pull request merged**
