### PR TITLE
Add lookups for users with missing profiles to middleware

### PR DESCRIPTION
**Pull request by agjohnson**
This fixes some logic around middleware and profiles. Adds some deeper testing
using request factory tests.

### CODE REVIEW

**Comment by ericholscher** [comment]
I'm guessing this is working around another bug, which is User Profile's no properly getting created when the user is created. That logic is here, and should be executed on user creation: https://github.com/rtfd/readthedocs.org/blob/f733088a0b8aec025826d4eaf2230293518f9028/readthedocs/core/models.py#L57

**Comment by agjohnson** [comment]
I assumed this might be due to migrations not adding the profiles for users existing before the migration. I'm not sure what's best here: fix our data and assume the signal is working, or ensure profile here as well. Maybe move some of this logic to a more central location?

**Comment by agjohnson** [comment]
i also almost used this for something else: https://github.com/skorokithakis/django-annoying. It performs automatic creation of `OneToOneField` with a special field instead of signals

**Comment by ericholscher** [comment]
Yea, I think the signals are broken in some case. It's been a lingering issue that I've never been able to track down. Switching to an implied 1to1 makes sense to me.

**Comment by agjohnson** [comment]
Okay, i replaced both bits of logic with django-annoying's `AutoOneToOneField`

**Comment by ericholscher** [comment]
LGTM.

**Pull request merged**
