### PR TITLE
Add per-command tracking to API out output detail page

### PR DESCRIPTION
**Pull request by agjohnson**
Sorry for another undigestable refactor, but no way to do this incrementally.

This adds per-command tracking inside build environments and on the build
detail page. Instead of lumping build output together, this starts to break out
output and errors into logical chunks that will be easier to understand by end
users. The front end pieces make use of KnockoutJS for data binding objects to
the DOM. It performs an ajax call to the build api to return updates on the
build object and commands that are attached to the build object.

The API has the following changes:

* :fire: API v1 build endpoint
* Makes API v2 build endpoint usable
* Adds API v2 command endpoint for adding commands
* API v2 build endpoint returns nested commands for easier API calls
* Adds necessary permissions to allow admin creation and authed/anonymous user
  read-only access

screen shot 2015-08-14 at 3 52 05 pm

### CODE REVIEW

**Comment by gregmuellegger** [comment]
Other than the inline comments: awesome!
That will make the build page so much better.

I haven't tried this locally, only looked at your screenshot. Can the output be scrolled horizontally?

**Comment by agjohnson** [comment]
And yeah, command/output elements are all independently horizontally scrollable

**Comment by ericholscher** [comment]
Looks good to me. :ship:

**Comment by gregmuellegger** [comment]
The UI really looks good in production :)

I noticed that the builds for the tickets #1028 #1572 do not contain any output:
https://readthedocs.org/projects/treeherder/builds/3256997/
https://readthedocs.org/projects/mongooseim/builds/3256523/

However, the users were able to provide a error message (stating something about wrong parameters to __init__). I wonder if the informational output got less after the deploy of this change.

**Pull request merged**
