### PR TITLE
Upgrade haystack to work with Django 1.8

### PR DESCRIPTION
**Pull request by deejay1**
Also fix pyquery part as it no longer raises an exception
on not finding it's query in the document.

This should fix some issues I've found when deploying RTD myself.

### CODE REVIEW

**Comment by ericholscher** [comment]
Thanks for the PR :)

**Comment by agjohnson** [comment]
I've reverted this merge in master due to some errors introduced, @deejay1 do you think you could resolve the issue with this commit and resubmit a PR?

It seems `html_to_index` isn't defined, and would throw an exception. We don't really support haystack anymore, so I don't have time to test a fix for this.

**Comment by deejay1** [comment]
I'll try to take a look at it in some spare time I wonder if we could just replace those commands with the custom ones from the docs...

**Comment by ranman** [comment]
anychance we could bring back in the lines that don't have html_to_index ? those two fixes for the string on search_index are great

**Pull request merged**
