### PR TITLE
Pin kombu to 4.3.0

### PR DESCRIPTION
**Pull request by stsewd**
Celery can install kombu>=4.2.0
https://github.com/celery/celery/blob/v4.1.1/requirements/default.txt#L3

But kombu>4.3.0 requires redis>=3.2
https://github.com/celery/kombu/blob/v4.5.0/requirements/extras/redis.txt#L1

### CODE REVIEW

**Comment by stsewd** [comment]
You can reproduce this running celery in a fresh installation

**Comment by humitos** [comment]
This will blow up in production probably. `kombu==4.3.x` requires a version of redis that it's not compatible with it.

We should pin `kombu==4.2.1` which is the version that we have currently installed in production.

**Comment by humitos** [comment]
In .org production we are using redis 3.2.7

**Comment by stsewd** [comment]
4.2.1 and 4.3.0 require the same version, actually a version of redis >= 2.10.5

https://github.com/celery/kombu/blob/v4.2.1/requirements/extras/redis.txt
https://github.com/celery/kombu/blob/v4.3.0/requirements/extras/redis.txt

**Pull request merged**
