### PR TITLE
Add docstring to DrfJsonSerializer so we know why it's there

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by humitos** [comment]
Hehe, the linting has failed.

If you run `pre-commit` it will fix two of the problems:

 - add the final .
 - make it a one line

You will still need to paraphrase it, because "This" is redundant :D

**Comment by humitos** [comment]
It seems that we are "more than strict" with the docstring ;)

**Comment by ericholscher** [comment]
Fixed!

**Comment by humitos** [comment]
Linting will still fail because of the usage of "This" as the first word of the docstring...

**Pull request merged**
