### PR TITLE
Allow anonymous read access for endpoints protected by APIRestrictedPermission

### LINKED ISSUE #1659: Handle logged out users on build detail page
Currently, due to some possibly aggressive permission checking on the build detail page, logged out users get a spinner, but API update requests receive a 403 response. Either logged out users should be able to query public projects, or this should back down to the static build detail page.

### PR DESCRIPTION
**Pull request by gregmuellegger**
This was not working as advertised in the docstring.

Fixes #1659.

### CODE REVIEW

**Comment by ericholscher** [comment]
I believe this is already addressed in #1672, with a more fully automated testing solution. Would love review of that.

**Comment by gregmuellegger** [comment]
True. I missed that.

**Comment by ericholscher** [comment]
The tests in this PR are more comprehensive and should be included in the other PR I think

**Comment by ericholscher** [comment]
Pushed them into the other PR.

**Pull request closed without merging**
