### PR TITLE
Add eslint using the airbnb config.

### PR DESCRIPTION
**Pull request by cmc333333**
In an effort to make the JS consistent, this adds an ESLint gulp task. ESLint
is *very* configurable, and has no defaults. Instead, this reaches for
airbnb's legacy config (which covers ES5), which is one of the most popular
configurations. As a last step, it turns off all of the rules which currently
fail. We can turn them on piecemeal, or override the airbnb style to use a
different format.

Rules to prioritize (as they likely indicate bugs):
* "array-callback-return": "off",
* "eqeqeq": "off",
* "guard-for-in": "off",
* "no-inner-declarations": "off",
* "no-loop-func": "off",
* "no-mixed-operators": "off",
* "no-undef": "off",
* "no-use-before-define": "off",
* "one-var": "off",

Also adds to CI, though I didn't come up with a great strategy to separate execution from the Python tests. This means that ESLint is running once per Travis configuration...

### CODE REVIEW

**Comment by ericholscher** [comment]
This is great! Thanks for this. I'll let @agjohnson look over it since he owns most of the front end, but I think this is a solid step forward.

**Comment by ericholscher** [comment]
I wonder if we can add this to tox, during the lint step? I don't know if it has a good support for installing JS deps, but it would be useful to be able to run it locally.

**Comment by cmc333333** [comment]
Thanks @agjohnson . I've been going down a rabbit hole of tox configurations to try to avoid setting up a whole python env, but I'm pleased with this state.

**Comment by agjohnson** [comment]
Great, yeah this is a solid addition. I've opened up #2909 to actually address the linting rules to a stricter level.

**Pull request merged**
