### PR TITLE
Allow installation of the project without a setup.py

### PR DESCRIPTION
**Pull request by agronholm**
With PEP 517, projects may no longer even have one in the future.

### CODE REVIEW

**Comment by ericholscher** [comment]
Looks good at first glance. Is there a way to verify a package is using the new stuff? I imagine not without executing it, because Python?

**Comment by agjohnson** [comment]
We could be inspecting `setup.cfg` for basic required metadata, but that doesn't ensure that setup.py is itself inspecting `setup.cfg`. We can probably be sure in the majority of cases though, with the exception being a package that moved to setup.py and left stale metadata in the setup.cfg.

**Comment by agjohnson** [comment]
@agronholm Revisiting this, I think what we want is to either catch the else case and report back to the user, or convert the elif back to else so that we are unconditionally trying to run `python setup.py` if the user wants the package installed and isn't using pip.

This should throw an error back at the user with `setup.py not found`, which should be enough. The best user experience here is reporting on what went wrong and how to fix it (disable install project) but we don't have a good pattern for this yet.

**Comment by agronholm** [comment]
> We could be inspecting setup.cfg for basic required metadata, but that doesn't ensure that setup.py is itself inspecting setup.cfg. We can probably be sure in the majority of cases though, with the exception being a package that moved to setup.py and left stale metadata in the setup.cfg.

Wait, why would we inspect setup.cfg?

> @agronholm Revisiting this, I think what we want is to either catch the else case and report back to the user, or convert the elif back to else so that we are unconditionally trying to run python setup.py if the user wants the package installed and isn't using pip.

Sure, if this is what you want. The current production code does nothing if `setup.py` is not found, regardless of whether the user has indicated that the project should be installed.

**Pull request merged**
