### PR TITLE
Remove build queue length warning on build list page

### PR DESCRIPTION
**Pull request by agjohnson**
This piece of UI was never updated to fit somewhere more cohesive in the UI and
I feel is a strange thing to expose directly to users. I think a better
application for this is in an eventual status page. A status page is not a
priority atm though.

### CODE REVIEW

**Comment by ericholscher** [comment]
I'm -0 on removing this. I think it's valuable for users who just see their build stuck in a Triggered state. What is the proposed replacement here? Just let users see their builds hang?

**Comment by humitos** [comment]
Maybe instead of fully removing it, just changing the wording/copy?

I don't think it's really useful to know as a user that there is a queue of 150 tasks.

Also, not sure but, the word `Triggered` isn't enough to communicate that it was "launched but not started yet"?

**Comment by ericholscher** [comment]
Yea, I think something along the lines of "We're experiencing an issue that might cause builds to be delayed" or something would be better than just removing this and having users have no knowledge that things are backed up, but will process.

**Comment by ericholscher** [comment]
Cool. I guess we can worry about it again if we start getting a lot of queue backups. At least the build objects are created now, as opposed to the old days where it was just sending builds into the abyss :)

**Comment by agjohnson** [comment]
And the hanging build objects are finally shown as terminated too! I think a lot of users assumed their builds were destroying our systems as they sat there.

I'll create an issue for updating the build list.

**Pull request merged**
