### PR TITLE
Remove description field from project forms and display

### LINKED ISSUE #3689: Remove project description field
I think we have good reason to just remove the description field. The dashboard page is public, but is not a reader focused page. This is extraneous UI for a maintainer dashboard page.

Having said that, we should evaluate what pulling this out looks like -- specifically:

* Can we simplify the import forms more by removing the description field?
* Does it make more sense to remove from modeling and just remove from forms and templates for now?
* What does the project dashboard page look like without a description block

### PR DESCRIPTION
**Pull request by bansalnitish**
Fixes #3689 
This PR removes project description field from project import form, project settings form and project detail display.

### CODE REVIEW

**Comment by stsewd** [comment]
> ...and add version listing with build details

I think this part is already addressed on #3673

**Comment by bansalnitish** [comment]
@stsewd PR #3673 is providing a different UI for version listing but this one is providing a vertical listing with information on the build date and state as well after removal of the description field (as in the screenshot).

**Comment by stsewd** [comment]
@bansalnitish this will conflict with #3673 which solve #3554. As general recommendation is better to keep the changes related to the issue that the PR is solving, anything else you can create a new issue if you consider or in this case make the suggestion on #3673.

**Comment by bansalnitish** [comment]
Actually I made these changes as per the suggestions here: https://github.com/rtfd/readthedocs.org/issues/3689#issuecomment-370050123
Shall I revert them?

**Comment by agjohnson** [comment]
Thanks for taking this on @bansalnitish !

#3689 is just the first step to making the dashboard page more usable. We're not yet ready to say what we want the front page version listing to be, so I'd rather avoid a redesign of this interface.

Perhaps start with just addressing #3689 here. My notes on what we want the listing to look like only tried to answer the question of whether we could replace the description field with more helpful content. We'll need a design process for the interface changes separately, but this will likely take a little while to form opinions on.

**Comment by bansalnitish** [comment]
Okay @agjohnson

**Comment by agjohnson** [comment]
@bansalnitish #3689 has progressed from a design decision state, so feel free to read that through for an update on our thoughts here. I've updated the ticket description with the points we'd like to address.

A UI update is still a ways off, so that can be broken out of this PR

**Comment by bansalnitish** [comment]
Hi @agjohnson, I have updated this PR according to the issue #3689!

**Comment by ericholscher** [comment]
Are we still happy with this implementation? I'm +1 on merging & deploying it.

**Pull request closed without merging**
