### PR TITLE
Add an application form for community ads

### PR DESCRIPTION
**Pull request by davidfischer**
My goal is to streamline the process for applying for community ads. Rather than an open ended email, I want to get applications that are immediately actionable.

I'm not sure how people feel about Google Forms, but they seem like a good fit here.

### CODE REVIEW

**Comment by ericholscher** [comment]
Looks good. I think you can make the image a file upload form, but it requires users login to Google. 

Would be neat to have this built into the ad server and perhaps switch to showing community ads via the ad server first, to slowly spin it up.

**Comment by davidfischer** [comment]
> I think you can make the image a file upload form, but it requires users login to Google.

This is correct. I'd erred on the side of not making users login but if we don't think that's a hurdle, I agree an upload is better.

> Would be neat to have this built into the ad server and perhaps switch to showing community ads via the ad server first, to slowly spin it up.

While it would be nice, a community ads application is super specific to Read the Docs. I'm not 100% sure it makes sense in the ad server.

**Comment by ericholscher** [comment]
Shall we ship this, and can iterate if we need?

**Comment by humitos** [comment]
:100: :heart_eyes:

**Pull request merged**
