### PR TITLE
Increasing repository url field size to 255

### PR DESCRIPTION
**Pull request by mrshoki**
100 was too small. We can easily end up with long urls when using private repositories and we need to add credentials within that url.

### CODE REVIEW

**Comment by ericholscher** [comment]
This would require a migration as well. Looks reasonable though.

**Comment by mrshoki** [comment]
Hi, thanks. I've added the migration script.

**Comment by hbetts** [comment]
If this one is to be merged in place of #1235, since this one was technically filed sooner, can it be updated to reference issue #1234 ?

**Comment by ericholscher** [comment]
Thanks!

**Pull request merged**
