### PR TITLE
Fixed issue with PRODUCTION_DOMAIN having more than 2 url parts

### PR DESCRIPTION
**Pull request by clarkperkins**
fix for #1697

### CODE REVIEW

**Comment by clarkperkins** [comment]
I've also changed the urlconfs to include `readthedocs` at the beginning - in my environment, this was required, but I'm not sure if there was some reason the `readthedocs` was missing, since all import statements, etc are prefixed with `readthedocs`.

**Comment by ericholscher** [comment]
This looks like a sane change. It would be great to see a test case that broke previously but now works.

**Comment by clarkperkins** [comment]
Sure, I can do that

**Comment by ericholscher** [comment]
Thanks :fireworks:

**Pull request merged**
