### PR TITLE
Fix links to other versions in mkdocs documentation footer

### LINKED ISSUE #1480: Documentation version selection broken with Mkdocs
If we switch versions from the options to release-3.7.0-1 on http://gluster.readthedocs.org/en/latest/
the resultant URL gets appended with "None" as in http://gluster.readthedocs.org/en/release-3.7.0-1/None/

also from any page, we cannot view the different versions of the documents, what I observed is the URL fired is mis matching the directory.

image

### PR DESCRIPTION
**Pull request by gregmuellegger**
The problem was that we didn't had access to the correct page name (the relative path to the source file without the .md suffix).

In order for this fix to work mkdocs needs to integrate mkdocs/mkdocs#721 and create a new release.

Blocked by mkdocs/mkdocs#721.
Fixes #1480.

### CODE REVIEW

**Comment by jhamman** [comment]
@gregmuellegger - https://github.com/mkdocs/mkdocs/pull/721 has been merged.  Is there anything keeping this from being merged.

**Comment by ericholscher** [comment]
mkdocs needs to make a release with this change in it. We could switch to using the development branch of mkdocs, but that feels like a bad solution.

**Comment by jhamman** [comment]
@ericholscher - I think waiting for the next release of mkdocs makes sense.  I'll keep bugging @d0ugal.

**Comment by d0ugal** [comment]
bug away, but I am not going to get to this until next month - getting married makes me super busy

**Comment by marcelstoer** [comment]
> getting married makes me super busy

Congrats!

> I am not going to get to this until next month

Hhmm, that would have been *last* month by now :wink: Would be really happy this issue (and all its dups) would see some progress.

**Comment by dnrce** [comment]
@gregmuellegger, is this unblocked by MkDocs 0.15.0?

**Comment by dirkrombauts** [comment]
I would like to see this one fixed too! I see there's a new MkDocs release as of a couple of days ago. Maybe that new version helps?

**Comment by ericholscher** [comment]
Merging this with the upgraded mkdocs release.

**Pull request merged**
