### PR TITLE
Replace symlink hack in settings/__init__.py with proper setup

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by ericholscher** [comment]
Not sure what the value of this is really. We need the __init__.py for it to be picked up as a python module, so it needs to exist. I guess we could just ship with it blank, but it's nice to be able to just say ``settings`` -- though I agree it is less explicit. So I'd be okay with just making it an empty file.

**Comment by techtonik** [comment]
@ericholscher this is required to make RTFD work on filesystems that don't support symlinks. But I don't know how to fix that in Git - Travis is red.

**Comment by techtonik** [comment]
@ericholscher fixed pep8 errors. Please take a look.

**Comment by ericholscher** [comment]
Great, thanks for the patch :)

**Pull request merged**
