### PR TITLE
Add basic rate limiting to builds.

### PR DESCRIPTION
**Pull request by ericholscher**
Pulled this old commit out of my history. At least worth considering before I delete it.

### CODE REVIEW

**Comment by agjohnson** [comment]
I'm -1 on null routing tasks over this limit. I think we should allow for a higher time limit on builds under the daily limit instead, reducing to a reasonable limit afterwards.

Also, this definitely needs UI additions, as dropping the tasks without warning/explanation is bad UX.

**Comment by mukulmishra** [comment]
Guis
Please don’t message me again.

**Comment by agjohnson** [comment]
@mukulmishra Not sure what you're referring to, no one here referenced you. If you are getting notifications on this issue, it's because you're subscribed to the repository notifications.

**Comment by mukulmishra** [comment]
Unsubscribe me Please

**Comment by agjohnson** [comment]
@mukulmishra we can't, you have to unsubscribe yourself.

**Pull request closed without merging**
