### PR TITLE
Support passing an explicit `index_name` for search indexing

### PR DESCRIPTION
**Pull request by ericholscher**
This is a bit of a hack, but it will work for now.

### CODE REVIEW

**Comment by safwanrahman** [comment]
I think we can move to the previous approach where we could pass the `index_name` in the `update` method by overriding the default `DocType` class of `django-elasticsearch-dsl`

**Comment by ericholscher** [comment]
Yea, that just leads to a lot of code that we're copy/pasting into our project, which feels more brittle.

**Comment by safwanrahman** [comment]
It will provide the wrong index name to the tasks that are running during the `     doc_obj.update(queryset.iterator())`. I think its better to avoide the hacky way if we can do from our end.
> Yea, that just leads to a lot of code that we're copy/pasting into our project, which feels more brittle.
I am hoping to implement it to the `django-elasticsearch-dsl` package as well. I think that time we do not need this much of code. But till then, I think its good to have that code in our project.

**Comment by ericholscher** [comment]
> It will provide the wrong index name to the tasks that are running during the ` doc_obj.update(queryset.iterator())`. I think its better to avoide the hacky way if we can do from our end.

I tested it and it seems to work fine.

**Comment by ericholscher** [comment]
Going to merge this so we can ship it, but we should come back to this.

**Pull request merged**
