### PR TITLE
Allow promos to be placed in the docs footer

### PR DESCRIPTION
**Pull request by davidfischer**
This allows promos to be placed in the footer instead of the normal left navigation for both the RTD and Alabaster themes.

screen shot 2017-11-14 at 10 00 03 pm
screen shot 2017-11-14 at 10 00 23 pm

### CODE REVIEW

**Comment by davidfischer** [comment]
I'm not entirely sure what this CI error is but it seems unrelated.

**Comment by agjohnson** [comment]
Yeah, I just resolved the error, feel free to merge/rebase.

Changes look good! I'll dive into a review here shortly to look at the technical bits, but visually, everything fits neatly there.

**Comment by ericholscher** [comment]
Looks good to me after a quick look over

**Comment by ericholscher** [comment]
Got it running locally and :+1:

**Comment by davidfischer** [comment]
I did generate `readthedocs/core/static/core/js/readthedocs-doc-embed.js` using gulp. Is there more to it?

**Comment by ericholscher** [comment]
Ah, nope! Sorry, just missed it in the PR :)

**Pull request merged**
