### PR TITLE
Update common to its latest version

### PR DESCRIPTION
**Pull request by humitos**
Get new configs from common.

### CODE REVIEW

**Comment by stsewd** [comment]
Looks like there are some py2 bits that can be removed https://github.com/rtfd/readthedocs.org/blob/50cb9a24045cf29c5719ffb92fd22cfdd54b0f34/readthedocs/config/models.py#L8

**Comment by stsewd** [comment]
We can remove the object inheritance (there are just a couple of places).

But we also have `pylint: logging-format-interpolation / Use % formatting in logging functions and pass the % p` which is in a lot of places and isn't a little to refactor :/, so is better to ignore the formatting check for now I guess :(

**Comment by humitos** [comment]
@stsewd I think making our code to pass the linter completely could be a "Good First Issue". Marking it as that to allow folk find it and helps us on this.

The actionable here is:

1. update our `common/` submodule to the latest `master`
1. run `tox -e lint` to find out the problems
1. adapt the code to fix those problems
1. run `tox -e lint` and make it succeed --iterating between 2 and 3

**Comment by stsewd** [comment]
If anyone wants to send a PR for this, I'd appreciate separating it in little chunks, so it's easy to review :)

**Comment by saadmk11** [comment]
@stsewd I have found 50+ `pylint: logging-format-interpolation / Use % formatting in logging functions and pass the % p` issues. how do you want the PRs to be separated ? should I add different PRs for Different files?

**Comment by stsewd** [comment]
I think for each constant or module.

**Comment by saadmk11** [comment]
Created All the PRs needed to fix the lint issues. :)

**Comment by saadmk11** [comment]
Glad I could Help ! :100:

**Pull request merged**
