### PR TITLE
RFC: view for project and its subprojects

### PR DESCRIPTION
**Pull request by xrmx**
We need something like the concept of an organization that collects more than one project. Fortunately we can do this kind of hierarchy using the subprojects. What we are missing though are a view that will return a project and its subprojects and the ability to restrict search results within a projects and its subprojects. This is what is inside this PR.
The work is still raw, tests are missing and there may be details to iron out but appear to work fine on my local installation :)
I'm posting this because I'd like to know if the idea is sound and is something you'll accept upstream.

### CODE REVIEW

**Comment by xrmx** [comment]
So it looks we really need to add the concept of publisher to a project. I think that we'll handle that on a separate app as it's probably useless upstream. So i think I'll drop the views and templates changes from this PR and keep just the search changes. What do you think?

**Comment by agjohnson** [comment]
It's not clear what the intended purpose of this change is, and the PR touches a number of pieces. Could you add more detail on why this is required and what needs to change?

**Comment by xrmx** [comment]
In this PR there is:
- ability to search project names inside a project and its subprojects
- a view that render a project and its subprojects (e376d12f9feb091c2fa38b6245cf3ad0f27c6413)

As I said above we'll need more changes to handle our use case and so with can ship the view on our own fork but the search changes are generic I'd like to have them upstream.

**Comment by agjohnson** [comment]
It's not really clear what the benefit from this changeset is, and it's touching a number of things, including substantial changes to our search. For that reason, I'm -1 on merging this without a discussion first on what needs to change and why.

Feel free to open up an issue to discuss these changes first, so we can discuss these changes separately. For the time being, none of this work looks related to a planned feature and is likely off of our development roadmap. I'll close this PR here so we can first discuss the changes.

**Pull request closed without merging**
