### PR TITLE
Remove version-compare.js

### LINKED ISSUE #1856: Branches and the "not using the most up to date version" note
In order to be able to add corrections to my docs, and FAQ entries and the like, I use release branches as the versions on RTD. For instance, I have a 0.6.x branch, then 0.7.x, 0.8.x.

This has worked fine for me in every way, except that it breaks the "You are not using the most up to date version of the library" feature.
1. When the feature is triggered, the message says "0.5.1 is the newest version"; however 1.0.3 is the newest version. 0.5.1 just happens to be the latest tag for which I build the docs (then I switched to using branches).
2. The feature is only triggered on doc pages built for a version that corresponds to a tag. If I visit the docs for 0.6.x, there will be no message at all.

My recommendations are the following:
1. Allow the target of the note to be configured, or just use the "default version" (the one / redirects to) instead of the most recent tag
2. Trigger it everywhere (perhaps change the wording a little bit, since you might be viewing the docs for a development branch that is ahead of the latest release, but I think there is value in indicating both when it is not the latest release and when it is not a release at all).

Example message: http://reprozip.readthedocs.org/en/0.4/packing.html

### PR DESCRIPTION
**Pull request by remram44**
Fixes #1856 by removing version-compare.js

TODO: rebuild statics

### CODE REVIEW

**Comment by remram44** [comment]
Your fabfile doesn't work, lxml doesn't compile without `CFLAGS=-I/usr/include/libxml2`, the barrier to work on RTD is kinda high...

**Comment by remram44** [comment]
Alright after having managed to setup all your Python dependencies, node.js, npm, gulp and all the other npm packages (I had never used npm before; can't you put this somewhere in [your ridiculous single-page so-called contributing "doc"](https://docs.readthedocs.org/en/latest/install.html)?), I'm hitting some kind of error from god-knows-what.

```
Warning: gulp-run is deprecated
[20:40:50] Using gulpfile /vagrant/gulpfile.js
[20:40:50] Starting 'build'...
[20:40:50] Building source files
[20:40:57] Browserify error: could not resolve dependency jquery : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/core/static-src/core/js/autocomplete.js) while parsing file: /vagrant/readthedocs/core/static-src/core/js/autocomplete.js
[20:40:57] Browserify error: could not resolve dependency readthedocs-client : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/projects/static-src/projects/js/tools.js) while parsing file: /vagrant/readthedocs/projects/static-src/projects/js/tools.js
[20:40:57] Browserify error: could not resolve dependency jquery : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/gold/static-src/gold/js/gold.js) while parsing file: /vagrant/readthedocs/gold/static-src/gold/js/gold.js
[20:40:57] Browserify error: could not resolve dependency knockout : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/projects/static-src/projects/js/import.js) while parsing file: /vagrant/readthedocs/projects/static-src/projects/js/import.js
[20:40:57] Browserify error: could not resolve dependency knockout : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/builds/static-src/builds/js/detail.js) while parsing file: /vagrant/readthedocs/builds/static-src/builds/js/detail.js
[20:40:57] Browserify error: could not resolve dependency jquery : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/donate/static-src/donate/js/donate.js) while parsing file: /vagrant/readthedocs/donate/static-src/donate/js/donate.js
[20:40:57] Browserify error: could not resolve dependency sphinx-rtd-theme : bower returns the module as known but not found (did you forget to run bower install ?) (/vagrant/readthedocs/core/static-src/core/js/doc-embed/sphinx.js) while parsing file: /vagrant/readthedocs/core/static-src/core/js/doc-embed/sphinx.js
```

For a website dedicated to documentation you are surprisingly bad at writing any kind of guide. I lost an hour for no reason whatsoever, now build your statics yourself. I will not be contributing to your project ever again and I am angry you made me try.

**Comment by agjohnson** [comment]
Instead of directing your anger at the maintainers because you are unfamiliar with the toolchain, try to raise a reasonable issue with our documentation. Calling it shit for the sake of calling it shit doesn't serve any purpose.

Our front end toolchain workflow is documented in length here:
http://docs.readthedocs.org/en/latest/development/standards.html#development-standards

**Comment by pydanny** [comment]
@remram44 You are not helping with your attitude. Not at all. Not with a project mostly powered by unpaid volunteers. A better way to handle this sort of issue is to do the following:

1. Open an issue **politely** stating that the project could use better documentation in the area of your complaint.
2. (optional) Take your notes on getting things working and submit them as a pull request.

**Comment by remram44** [comment]
All that's left is for one of you team members, who know how your frontend setup works, to run "gulp". Surely you'll manage.

As for your doc, I just want you to know that I lost that much time. That your fabfile doesn't work on Debian because of lxml. Fix it or not, I don't really care, now I have to handle the [public shaming that your co-founder unleashed on me on Twitter](https://twitter.com/ericholscher/status/694318734647754752) instead (really makes me miss not being a part of your community... or does it?)

**Comment by pydanny** [comment]
@remram44 I thought about your discussion here and I realized I probably came on too strong. I should have tried to work through things with you in a more rational manner. You seem passionate about doing stuff and that's awesome. Why not be friends? I've made friends through adversity before, why not now?

I really was about to try. And then...

Then I noticed the nasty parts of your comments were gone. Changed. You took them out. Deleted them. No longer do you complain bitterly about a documentation site that doesn't document its installation to standard you demand.

At first I was infuriated. But then I realized that's the wrong way.

Why?

Because I think you removed those comments because you, like me, realized we were going down the wrong path. And you know what? I can understand why you might have deleted the more angry part of your writing in this pull request.

So let's not fight. Let's work together. Instead of bickering, let's channel our passion for open source and make awesome stuff.

**Pull request closed without merging**
