### PR TITLE
Allow superusers to pass admin & member tests for projects

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by agjohnson** [comment]
Also, what is the context for this change? A description here would be helpful.

**Comment by ericholscher** [comment]
Mostly I want to be able to trigger builds for users, which is now hidden behind an admin block. But it will also be useful for other places we're running the check as well, so we can see more info.

**Comment by ericholscher** [comment]
Believe the .com overrides these methods, so it shouldn't have much effect.

**Comment by agjohnson** [comment]
Roger 👍

**Pull request merged**
