### PR TITLE
Create vm.rst

### PR DESCRIPTION
**Pull request by MonamiB**
Added information on local installation and setup of RTD in a VM.

### CODE REVIEW

**Comment by ericholscher** [comment]
This is great. I'll look over it this week and get it merged, thanks!

**Comment by MonamiB** [comment]
Thanks, Eric! Hope this is useful.

Found one major issue - I had erroneously shared a confidential VM alias in
here. Need a way to get rid of that permanently! Would you know how?

On Mon, Jun 1, 2015 at 8:58 PM, Eric Holscher <notifications@github.com>
wrote:

> Merged #1308 <https://github.com/rtfd/readthedocs.org/pull/1308>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1308#event-319019399>.
>



-- 
Thanks!

*Monami Bhattacharya*
Seller Platform - Documentation

**Comment by ericholscher** [comment]
I think you'd have to talk to GitHub support, I can remove it with a
commit, but it would always be in the git history.

On Mon, Jun 1, 2015 at 8:43 AM, MonamiB <notifications@github.com> wrote:

> Thanks, Eric! Hope this is useful.
>
> Found one major issue - I had erroneously shared a confidential VM alias in
> here. Need a way to get rid of that permanently! Would you know how?
>
> On Mon, Jun 1, 2015 at 8:58 PM, Eric Holscher <notifications@github.com>
> wrote:
>
> > Merged #1308 <https://github.com/rtfd/readthedocs.org/pull/1308>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rtfd/readthedocs.org/pull/1308#event-319019399>.
> >
>
>
>
> --
> Thanks!
>
> *Monami Bhattacharya*
> Seller Platform - Documentation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1308#issuecomment-107595645>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by MonamiB** [comment]
Ok, I found this - https://help.github.com/articles/remove-sensitive-data/

Can you possibly try it?

On Mon, Jun 1, 2015 at 9:16 PM, Eric Holscher <notifications@github.com>
wrote:

> I think you'd have to talk to GitHub support, I can remove it with a
> commit, but it would always be in the git history.
>
> On Mon, Jun 1, 2015 at 8:43 AM, MonamiB <notifications@github.com> wrote:
>
> > Thanks, Eric! Hope this is useful.
> >
> > Found one major issue - I had erroneously shared a confidential VM alias
> in
> > here. Need a way to get rid of that permanently! Would you know how?
> >
> > On Mon, Jun 1, 2015 at 8:58 PM, Eric Holscher <notifications@github.com>
> > wrote:
> >
> > > Merged #1308 <https://github.com/rtfd/readthedocs.org/pull/1308>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rtfd/readthedocs.org/pull/1308#event-319019399>.
> > >
> >
> >
> >
> > --
> > Thanks!
> >
> > *Monami Bhattacharya*
> > Seller Platform - Documentation
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/rtfd/readthedocs.org/pull/1308#issuecomment-107595645>
> > .
> >
>
>
>
> --
> Eric Holscher
> Maker of the internet residing in Portland, Oregon
> http://ericholscher.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1308#issuecomment-107597652>
> .
>



-- 
Thanks!

*Monami Bhattacharya*
Seller Platform - Documentation

**Comment by ericholscher** [comment]
I went ahead and force pushed the repo back to an unmerged state, so these commits never happened. This pull request will need to be removed though.

**Comment by MonamiB** [comment]
Done! Submitted new file with safer content.

On Mon, Jun 1, 2015 at 9:23 PM, Eric Holscher <notifications@github.com>
wrote:

> I went ahead and force pushed the repo back to an unmerged state, so these
> commits never happened. This pull request will need to be removed though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1308#issuecomment-107602934>
> .
>



-- 
Thanks!

*Monami Bhattacharya*
Seller Platform - Documentation

**Comment by MonamiB** [comment]
Hey, so last ditch effort. I deleted the repo, but vm.rst is still showing
here -
https://github.com/rtfd/readthedocs.org/tree/2c473b4e2ab198caf2ce02da7557083a18546fa7/docs/custom_installs

Is there a way for you to delete this branch altogether?

On Mon, Jun 1, 2015 at 9:23 PM, Eric Holscher <notifications@github.com>
wrote:

> I went ahead and force pushed the repo back to an unmerged state, so these
> commits never happened. This pull request will need to be removed though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1308#issuecomment-107602934>
> .
>



-- 
Thanks!

*Monami Bhattacharya*
Seller Platform - Documentation

**Pull request merged**
