### PR TITLE
Optimize some of the images to reduce the bandwidth

### PR DESCRIPTION
**Pull request by anthonyryan1**
Noise textures compress very poorly. By replacing a couple of the textures
with comparable SVGs, it's possible to reduce the home page by ~50 KB.

### CODE REVIEW

**Comment by gregmuellegger** [comment]
Cool idea. Here is a comparison rendered on my system with Firefox (left is the new SVGs, right the old PNGs):

screen1

LGTM

@anthonyryan1: do you expect any browser compatibility problems? http://caniuse.com/#search=svg <-- looks fine IMO

**Comment by anthonyryan1** [comment]
There shouldn't be any compatibility problems, any browser that doesn't support SVGs will fall back to a solid color background without the noise texture.

**Comment by destroyerofbuilds** [comment]
:+1:

**Comment by gregmuellegger** [comment]
Cheers @anthonyryan1 
I've merged this.

**Pull request merged**
