### PR TITLE
Upgrade requests version

### PR DESCRIPTION
**Pull request by davidfischer**
This is related to a production issue with the older requests version.

### CODE REVIEW

**Comment by humitos** [comment]
Be careful with requests upgrade since it's not fully compatible with all versions of docker-py: https://github.com/rtfd/readthedocs.org/pull/3243#issuecomment-350936603

**Comment by davidfischer** [comment]
If anything, we want to upgrade further. https://github.com/docker/docker-py/commit/3b95da3ea48c3f60f133cdefe1382fce5d44a770

**Comment by humitos** [comment]
I agree. I'd like to upgrade `docker` and `requests` to the latest version available. We need to consider that RTD servers will be using `17.05.0~ce-0~ubuntu-xenial` which is also not the latest docker engine. So, we need to be carefull that these three dependencies work all together :)

**Comment by ericholscher** [comment]
Do we know if these are safe? Did we hotfix prod for the issue the other day with this version? @agjohnson

**Comment by agjohnson** [comment]
I used `2.9.1` (system version) as the first version that wasn't reproducing the error. I don't see a reason to not go higher though. I didn't test this at all though

**Comment by agjohnson** [comment]
This is needed. Higher bump can be done later.

**Pull request merged**
