### PR TITLE
Remove hiredis

### PR DESCRIPTION
**Pull request by ericholscher**
This might be the cause of our random celery disconnects.

Refs https://github.com/celery/celery/issues/2606#issuecomment-413274023

### CODE REVIEW

**Comment by ericholscher** [comment]
I've hotfixed this to see if it solves our disconnect issues.

**Comment by ericholscher** [comment]
Yep, I hotfixed it that way, but it got reinstalled whenever we installed the prod dependencies.

**Comment by humitos** [comment]
I'm merging this PR and running to hotfix this:

```
celery -A readthedocs control shutdown
pip uninstall hiredis
```

Then,

    supervisorctl restart build

and,

    supervisorctl restart web

**Comment by humitos** [comment]
I also restarted these on webs

    supervisorctl restart celery:celery-beat celery:celery-web celery:celery-web02 web

**Comment by humitos** [comment]
Since we applied this we have not experience more issues with workers being disconnected! I think this is a win :tada:

**Pull request merged**
