### PR TITLE
static: use modern getJSON callbacks

### PR DESCRIPTION
**Pull request by xrmx**
Use done() and fail() instead of complete() and success() that got
removed in jquery 3.0.

### CODE REVIEW

**Comment by stsewd** [comment]
Thanks, you need to regenerate the minified js https://docs.readthedocs.io/en/latest/development/standards.html#getting-started

**Comment by xrmx** [comment]
@stsewd i've not regerated them on purpose to avoid issues with review / merge latency. If you are fine with the PR i can build the static files.

**Comment by stsewd** [comment]
Those are deprecated in version 2? We still use 2.0.3

https://github.com/rtfd/readthedocs.org/blob/110347355921fe82aee57ef04160a7a3477dedef/bower.json#L17-L17

**Comment by xrmx** [comment]
Are deprecated since 1.5 or 1.6 can't remember.

**Comment by xrmx** [comment]
Updated branch with rebuilt static files

**Comment by xrmx** [comment]
Updated PR to fix merge conflict

**Comment by xrmx** [comment]
New build conflicts, what about starting to open PR with only the source changed and have a commiter rebuild the static files?

**Comment by stsewd** [comment]
I was thinking about that too, I don't remember what the core team said about that

**Comment by ericholscher** [comment]
Tested this locally and it looks good. 👍

**Pull request merged**
