### PR TITLE
Anonymize IP addresses for Google Analytics

### PR DESCRIPTION
**Pull request by davidfischer**
For RTD's analytics purposes, we never need IP addresses more granular than this.

https://support.google.com/analytics/answer/2763052?hl=en

### CODE REVIEW

**Comment by davidfischer** [comment]
In fact if anything, we could further anonymize the data but I don't think that's supported.

**Comment by ericholscher** [comment]
💯

**Comment by ericholscher** [comment]
Thanks for looking into this!

**Comment by seibert** [comment]
Is there an ETA for when this will be rolled out to the website?

**Comment by stsewd** [comment]
@seibert it's deployed right now :)

**Comment by davidfischer** [comment]
This is out and live for readthedocs.org and has been for a month or so. If you have an analytics debugger, you can verify this as in the below screenshot.

screen shot 2018-03-20 at 2 29 21 pm

However, individual docs sites need to be built again after this change and the relevant theme change https://github.com/rtfd/readthedocs-sphinx-ext/pull/37 was pushed to production and they have to take the updated theme. So depending on when and how the documentation you are browsing was built, it may not have taken effect yet. This is currently a limitation of our analytics that they are part of the documentation build process rather than a JS file we link to that can be updated independently of a build. It's on my list to change.

**Pull request merged**
