### PR TITLE
Remove launchpad.py seem to be ununsed.

### PR DESCRIPTION
**Pull request by Carreau**
Untouch since 2011
Launchpad backend seem to use Bzr directly.

### CODE REVIEW

**Comment by ericholscher** [comment]
This needs to be removed in a few other places as well, including the `backends/__init__.py` file. Otherwise I'm +1 for dropping this special casing. We don't have a huge number of bzr projects, and launchpadlib is a big dependency.

**Comment by Carreau** [comment]
> This needs to be removed from backends/__init__.py file also.

Do you mean removing 
```
backend_cls = {
    ...
    'launchpad': bzr.Backend,   # this one ?
    ...
}
``` 

? Because this particualar file is not imported anywhere

**Comment by ericholscher** [comment]
Correct. That file is used here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/models.py#L36

**Comment by Carreau** [comment]
Oh, by `this` I ment `readthedocs/vcs_support/backends/launchpad.py` I saw that `readthedocs/vcs_support/backends/__init__.py` was used.

 Anyway I pushed a commit to remove it.

**Comment by ericholscher** [comment]
Ah yea, I just meant the reference to `launchpad`, as it was the only other result in a grep.

Thanks for this :)

**Pull request merged**
