### PR TITLE
Add COC

### PR DESCRIPTION
**Pull request by ericholscher**
This updates #2362 and adds the COC to the docs.

### CODE REVIEW

**Comment by agjohnson** [comment]
I commented this on the last CoC PR:
https://github.com/rtfd/readthedocs.org/pull/2362#issuecomment-241515189

It sounds like we could adopt a fork of Django's CoC instead of this one. The code of conduct here is particularly talking about maintainers, I want this to extend to non-contributing users as well.

**Comment by ericholscher** [comment]
Good call -- I think we're implicitly under the Python COC as well, but <3 Django's in general.

**Comment by ericholscher** [comment]
Updated.

**Comment by agjohnson** [comment]
Looks good to me 👍

**Pull request merged**
