### PR TITLE
Add note about mercurial on tests

### PR DESCRIPTION
**Pull request by stsewd**
I just add a note about mercurial to solve #3320.

### CODE REVIEW

**Comment by agjohnson** [comment]
Thanks for the update @stsewd !

**Comment by agjohnson** [comment]
Actually, if we are already requiring this for tests, perhaps we just install mercurial in our testing requirements?

**Comment by stsewd** [comment]
Sure, that's better (I didn't know mercurial was written in python D:).

**Comment by stsewd** [comment]
@agjohnson Is it okay if the Mercurial version is not specified?
And can I squash the commits later or it's fine like that?

**Comment by agjohnson** [comment]
Normally, it would be fine -- we've been pinning our testing dependencies lately because they break in CI so often though. Pinning to the latest release should be fine

**Comment by stsewd** [comment]
@agjohnson Ready, I set the version to the latest (4.4.2)

**Comment by ericholscher** [comment]
Looks great, thanks!

**Pull request merged**
