### PR TITLE
[#3835] Move core/validators

### PR DESCRIPTION
**Pull request by mashrikt**
I have moved core/validators to projects/validators.
Fixed the subsequent imports.
Added a relevant migration. I suspect there are some issues here.

### CODE REVIEW

**Comment by stsewd** [comment]
@mashrikt hi, why did you close this PR?

**Comment by mashrikt** [comment]
@stsewd I apologize for my mistake. I thought I badly messed it up and was looking to delete to the PR. Instead I mistakenly closed the PR. 
I have since made another PR for the task.

**Comment by stsewd** [comment]
@mashrikt don't worry, I just wanna know that everything was ok :).

Closed in favor of #3850

**Comment by mashrikt** [comment]
Thanks @stsewd

**Pull request closed without merging**
