### PR TITLE
Organized requirements.

### PR DESCRIPTION
**Pull request by syndbg**
Just cloned the project with intentions to contribute functionality and I noticed that the requirements are all over the place.

This should make `pip requirements` easier to maintain and find.
I updated all (__hopefully__) requirements paths.

### CODE REVIEW

**Comment by agjohnson** [comment]
Thanks for this update! It's one a change we have sitting on a couple cleanup branches already. This will have to sit for a while, as our deployments are going through an update currently and will all need to be changed to deploy with this branch.

**Comment by ericholscher** [comment]
I'm +1 on this change

**Comment by syndbg** [comment]
@ericholscher  Alright, will do.

**Comment by ericholscher** [comment]
Merged, thanks :)

**Pull request closed without merging**
