### PR TITLE
New languages

### PR DESCRIPTION
**Pull request by julienmalard**
I added a few Pakistani and all officially recognised Guatemalan languages. I am submitting a new pull request as I can't seem to be able to rebase my original request (ref #3369) and have a clean working tree.
I hope that this pull request will be acceptable!

### CODE REVIEW

**Comment by agjohnson** [comment]
Thanks for reworking your branch! This may generate a migration, we should add that here as well if so. Does `makemigrations` give a project migration?

**Comment by julienmalard** [comment]
Thank you! I will try on Monday and let you know.

Just to be sure that I don't make another mistake: all I should do is run


    python manage.py makemigrations


...and then see if any migrations are made (and commit & push them if necessary)?


Thanks!

-Julien

________________________________
દ્વારા: Anthony <notifications@github.com>
મોકલ્યું: 09 માર્ચ 2018 20:28:40
પ્રતિ: rtfd/readthedocs.org
Cc: Julien Malard; Author
વિષય: Re: [rtfd/readthedocs.org] New languages (#3759)


Thanks for reworking your branch! This may generate a migration, we should add that here as well if so. Does makemigrations give a project migration?

**Comment by julienmalard** [comment]
Hello,

I can't seem to be able to get a successful migration run on my computer (it says that I need to install packages which I have in fact installed)...any chance you could help me out with the migration?

Many thanks,
Julien Malard

**Comment by RichardLitt** [comment]
@agjohnson Is there a document on how to do this, somewhere?

**Comment by humitos** [comment]
@RichardLitt @julienmalard I think the best place to read about this is the Django official documentation at https://docs.djangoproject.com/en/2.0/topics/migrations/

@julienmalard in case you still have problems, please paste the output of the command that it's failing so we can see what it's happening in your side.

**Comment by julienmalard** [comment]
Hello all,

Many thanks for your support! I figured out the mistake (seems that some build dependencies were not explicitly listed in the requirements file).
Here is the output from the migration run. I think it means that it worked? I will push the repository now.

> (venv) C:\Users\jmalar1\PycharmProjects\readthedocs.org>python manage.py makemigrations
> System check identified some issues:
> 
> WARNINGS:
> ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
> ?: (guardian.W001) Guardian authentication backend is not hooked. You can add this in settings as eg: `AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', 'guardian.backends.ObjectPermissionBackend')`.
> Migrations for 'builds':
>   0005_auto_20180315_1604.py:
>     - Alter field error on build
>     - Alter field output on build
>     - Alter field state on build
>     - Alter field type on build
>     - Alter field privacy_level on version
>     - Alter field slug on version
>     - Alter field type on version
>     - Alter field from_slug on versionalias
>     - Alter field to_slug on versionalias
> Migrations for 'comments':
>   0002_auto_20180315_1604.py:
>     - Alter field decision on moderationaction
>     - Alter field date on nodesnapshot
> Migrations for 'gold':
>   0002_auto_20180315_1604.py:
>     - Alter field level on golduser
> Migrations for 'integrations':
>   0003_auto_20180315_1604.py:
>     - Create proxy model BitbucketWebhook
>     - Create proxy model GenericAPIWebhook
>     - Create proxy model GitHubWebhook
>     - Create proxy model GitLabWebhook
>     - Alter field integration_type on integration
> Migrations for 'oauth':
>   0009_auto_20180315_1604.py:
>     - Alter field clone_url on remoterepository
>     - Alter field ssh_url on remoterepository
>     - Alter field vcs on remoterepository
> Migrations for 'projects':
>   0024_auto_20180315_1604.py:
>     - Alter field canonical on domain
>     - Alter field count on domain
>     - Alter field allow_promos on project
>     - Alter field comment_moderation on project
>     - Alter field conf_py_file on project
>     - Alter field default_version on project
>     - Alter field documentation_type on project
>     - Alter field has_valid_webhook on project
>     - Alter field language on project
>     - Alter field privacy_level on project
>     - Alter field programming_language on project
>     - Alter field python_interpreter on project
>     - Alter field repo_type on project
>     - Alter field suffix on project
>     - Alter field theme on project
>     - Alter field version_privacy_level on project
> Migrations for 'redirects':
>   0002_auto_20180315_1604.py:
>     - Alter field redirect_type on redirect
>     - Alter field to_url on redirect

**Comment by agjohnson** [comment]
@julienmalard oops, it looks like you got all of the field changes in a migration set! Make sure you run the `migrate` step of installation before generating and new migrations:
http://docs.readthedocs.io/en/latest/install.html

**Comment by julienmalard** [comment]
Hello,


I reverted the commit, ran python manage.py migrate, followed by python manage.py makemigrations. Is it ok now?


Thanks!

-Julien

________________________________
દ્વારા: Anthony <notifications@github.com>
મોકલ્યું: 15 માર્ચ 2018 19:54:33
પ્રતિ: rtfd/readthedocs.org
Cc: Julien Malard; Mention
વિષય: Re: [rtfd/readthedocs.org] New languages (#3759)


@julienmalard<https://github.com/julienmalard> oops, it looks like you got all of the field changes in a migration set! Make sure you run the migrate step of installation before generating and new migrations:
http://docs.readthedocs.io/en/latest/install.html

**Comment by agjohnson** [comment]
Hrm, that doesn't seem to have helped. There are still a large number of spurious migrations included.

**Comment by julienmalard** [comment]
That is very odd... is there any chance you could clone my fork and then run the migrations on your system, if you think that could work? If there is anything I could do on my system instead, please do let me know.


-Julien

________________________________
દ્વારા: Anthony <notifications@github.com>
મોકલ્યું: 20 માર્ચ 2018 19:44:21
પ્રતિ: rtfd/readthedocs.org
Cc: Julien Malard; Mention
વિષય: Re: [rtfd/readthedocs.org] New languages (#3759)


Hrm, that doesn't seem to have helped. There are still a large number of spurious migrations included.

**Comment by agjohnson** [comment]
If you can, just create a migration for the `projects` application and remove any unwanted migrations from that file. There are likely skipped migrations currently around help_text updates.

**Comment by julienmalard** [comment]
Better? :)

**Comment by julienmalard** [comment]
Hello,
I just wanted to ask whether what I have done was correct/sufficient or if I would need to do something else for this pull request to be acceptable.
Thanks!
Julien

**Comment by stsewd** [comment]
Looks like there is a problem with the migration. Can you rebase your branch to the current master and re-generate the migration? Also can you use a named migration? `python manage.py makemigrations --name changed_my_model your_app_label`

**Comment by julienmalard** [comment]
Sure, will do that now. (By the way, does the migration have to be done on Python 2, or should it not make a difference?)
Thanks for the help!

**Comment by stsewd** [comment]
It shouldn't make any difference

**Comment by humitos** [comment]
I'm assign this to myself to merge after the migration that is taking place this weekend.

> NOTE: tests are not passing, we need to rebase with master and probably update the migration.

**Comment by agjohnson** [comment]
Unassigning for now, cleaning this PR up is going to take a bit of work and not something core team can focus on ATM.

**Comment by ericholscher** [comment]
Fixed up this migration, and it should be ready to merge. 👍

**Comment by julienmalard** [comment]
Many thanks!

**Pull request merged**
