### PR TITLE
Refactor: fileify and _manage_imported_files

### PR DESCRIPTION
**Pull request by shivanshu1234**
Ref: https://github.com/rtfd/readthedocs.org/issues/3775

**fileify**  and **_manage_imported_files** have been moved from 

/readthedocs/projects/tasks.py

to

/readthedocs/builds/tasks.py

Only two tasks have been moved so that first I can get a confirmation that I am going on the right track.
After this, other tasks which will be moved:

* send_notifications
* email_notification 
* webhook_notification
* finish_inactive_builds

And if there are other tasks which require refactoring, I would be happy to do those as well.

### CODE REVIEW

**Comment by shivanshu1234** [comment]
Closing this as it has become old and has developed conflicts.

**Comment by shivanshu1234** [comment]
Closing this as it has become old and developed conflicts. I will make a new PR for this.

**Comment by agjohnson** [comment]
Note: you can also rebase your work or merge master into your branch instead of making new PRs

**Comment by shivanshu1234** [comment]
OK, I will do that the next time. Thank you.

**Pull request closed without merging**
