### PR TITLE
Fixes internal reference

### PR DESCRIPTION
**Pull request by bansalnitish**
This PR fixes an internal reference in ``abandoned-projects.rst``

### CODE REVIEW

**Comment by agjohnson** [comment]
The reference looks like it should work just fine, and appears to do so in testing this in our docs. Is there a specific issue this is addressing?

**Comment by stsewd** [comment]
I can also see that this works fine on the docs. @bansalnitish this references are created implicitly from the title http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#implicit-hyperlink-targets

**Comment by bansalnitish** [comment]
@agjohnson @stsewd I changed the reference from implicit to explicit because implicit references are mostly error-prone when we rename sections or try to duplicate them. Using ref is better than using links to sections because it works across files, when section headings are changed, and for all builders that support cross-references.

**Comment by stsewd** [comment]
@bansalnitish By the way there is a PR in progress https://github.com/rtfd/readthedocs.org/pull/3624 to catch that kind of errors on the docs.

**Comment by bansalnitish** [comment]
That is great @stsewd!

**Comment by bansalnitish** [comment]
HI @stsewd, any updates on this!

**Comment by stsewd** [comment]
@bansalnitish Not sure if this PR is really needed since  the current ref works just fine.

**Comment by bansalnitish** [comment]
Thanks, @stsewd! I am closing this one!

**Pull request closed without merging**
