### PR TITLE
oauth/services: don't abuse log.exception

### PR DESCRIPTION
**Pull request by xrmx**
log.exception should not be used outside exception handlers

### CODE REVIEW

**Comment by xrmx** [comment]
Because else is not for unhandled exceptions but for code that does not raise *any* exceptions:
```
>>> try:
...   raise ValueError
... except KeyError:
...   pass
... else:
...   print('am not here')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError
```

**Comment by humitos** [comment]
Yeah, I got confused. Sorry about that.

So, we probably want to refactor that code since if the `else` is excecuted when any exception was risen, why we are logging an error? It doesn't make sense to me.

**Comment by xrmx** [comment]
Because of  ``` if resp.status_code == 201:``` and the likes in the try block.

**Comment by humitos** [comment]
I understand. I'd say that code needs to be rewritten with an easy to follow and clear flow, then :)

**Comment by xrmx** [comment]
If you have time I'd do some audit of try-else usage in RTD, the next PR is fixing another misusage :)

**Comment by ericholscher** [comment]
Thanks!

**Pull request merged**
