### PR TITLE
Addressed cleanup issue #5327

### PR DESCRIPTION
**Pull request by rshrc**
the function get_contribution_details() was not being used along with allow_email attribure in core/models.py

### CODE REVIEW

**Comment by ericholscher** [comment]
Thanks for the PR -- this needs a migration since you are changing a model. There are docs for that here: https://docs.djangoproject.com/en/2.1/topics/migrations/

**Comment by rshrc** [comment]
> Thanks for the PR -- this needs a migration since you are changing a model. There are docs for that here: https://docs.djangoproject.com/en/2.1/topics/migrations/

So I'll just migrate and send another PR.

**Comment by ericholscher** [comment]
You should send it in this same PR -- just push to your `master` branch and the PR will update.

**Comment by rshrc** [comment]
Okay @ericholscher I'll do it

**Pull request closed without merging**
