### PR TITLE
Remove logic around finding config file inside directories

### PR DESCRIPTION
**Pull request by sriks123**
Fixes issue #4669

### CODE REVIEW

**Comment by sriks123** [comment]
Hi @stsewd can you please review this?

**Comment by stsewd** [comment]
@sriks123 any reason why you closed #4714?

**Comment by sriks123** [comment]
@stsewd I closed #4714 due to some problems in that branch which I created

**Comment by sriks123** [comment]
@stsewd thanks

**Comment by stsewd** [comment]
@agjohnson can we merge this?

**Comment by ericholscher** [comment]
Looks good. 👍

**Pull request merged**
