### PR TITLE
Remove unused form

### PR DESCRIPTION
**Pull request by stsewd**
We never finished this feature, but is coming soon!

There are more to remove, but I need to investigate is we are still using some the `UPLOAD_ROOT` setting and the `uploaded` fields from the version model,

Added in https://github.com/rtfd/readthedocs.org/commit/c33c84d007ae1daed8cd9b12389946c7baa38910

### CODE REVIEW

**Comment by stsewd** [comment]
We need to check if we have projects with versions `uploaded=True`, if not, we can remove that field.

**Comment by humitos** [comment]
> We need to check if we have projects with versions `uploaded=True`, if not, we can remove that field.

We have 113 version with `uploaded=True` (80 projects in total). Although, I don't think this is used anywhere in the code and could be removed. We can merge this PR and decide what to do with them later, though.

**Comment by humitos** [comment]
@stsewd we should close this PR or finish and merge it.

We could also mark it as "Good First Issue" asking the community to finish it on the other hand if we can tackle it now.

**Comment by stsewd** [comment]
We can merge this and have another PR to remove the `upload` field and setting.

**Pull request merged**
