### PR TITLE
Specify python3 in installation instructions.

### PR DESCRIPTION
**Pull request by shivanshu1234**
Closes https://github.com/rtfd/readthedocs.org/issues/5550

### CODE REVIEW

**Comment by jasonaowen** [comment]
> Thanks, I wonder if can just use `python -m venv venv`

That would work (I just tested it), but we'd also need to update at least the Ubuntu required packages to include `python3-venv`:

```
$ python3 -m venv venv 
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

**Comment by shivanshu1234** [comment]
Yes, can confirm this. [Ubuntu Bug #1532231](https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1532231)

**Comment by jasonaowen** [comment]
It looks like the `python3-venv` packages exists on [Xenial (16.04)](https://packages.ubuntu.com/xenial/python3-venv) and later. After installing it on my 18.04 machine, I was able to run `python -m venv venv` successfully, and it created an environment where `python` was linked to the system `python3.6`.

**Comment by humitos** [comment]
Thanks!

**Pull request merged**
