### PR TITLE
Version compare warning text

### PR DESCRIPTION
**Pull request by benjaoming**
image

The old text mentions "library", however we want to reduce user confusion here, since "library" can have much different meanings in our project.

Since there are some projects on RTD that are documentation only and not necessarily connected to software releases, we suggest to go for just "documentation".

I also built the frontend, but I'm not really sure if that's common practice to do in the PR?

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for the feedback  @humitos - I have studied https://github.com/rtfd/readthedocs.org/issues/3481 -- however, I cannot find any particular opinions around the wording of the banner? I can see that you have contributed to analyzing various complex scenarios. But this PR doesn't try to play around with any of this.

To keep this constructive, I think it's better to not vote against small incremental changes that arguably improves an existing text. This is a documentation project, so I hope you get what I mean :)

It seems unlikely and highly speculative that someone has based their warning banner on the word "library" and I can't really see how the suggestion to write something more general would confuse users of a software library.

I'd like to avoid the extension solution for now because it will not have any backwards applicability (unless I dig around and rebuild old branches, overwrite tags etc). But thanks for writing it.

I think warning users about reading old doc versions is an issue that needs to be solved universally for RTD. Although it's a bit quirky, I'm happy with the current banner "injection" and just suggesting a simple text change.

**Comment by benjaoming** [comment]
Supposing that it's a hot potato, it's great to wait for a wider approval of the text change.

**Comment by humitos** [comment]
I re-read your PR and I think I'm changing my mind.

> You are not reading the most recent version of this documentation. X.Y.Z is the latest version available.

This sounds generic enough without mentioning _library_, _software_ or anything tied to a particular "topic" but _documentation_ which is what it is in the end.

So, forget what I said before and thanks for your reply :)

**Comment by ericholscher** [comment]
Good change. The frontend assets will get regenerated before deploy, so I think it's fine as is. 👍

**Pull request merged**
