### PR TITLE
Pass query string when redirecting, fixes #2595

### LINKED ISSUE #2595: Support query args in redirects
A redirect should be able to pass on query args. Currently, a redirect hit with query args 404s.

### PR DESCRIPTION
**Pull request by andrew**
Took a stab at fixing #2595, not worked with flask before but this seems to do the trick.

### CODE REVIEW

**Comment by ericholscher** [comment]
Looks great! I'll get it tested locally and then merged in :)

**Comment by agjohnson** [comment]
This file should also be removed, as should probably most anything under `deploy/`, it's no longer used. The correct version is a private repository now.

**Comment by humitos** [comment]
> The correct version is a private repository now.

Do we still need this fix in the private repo version or it was already fixed?

**Comment by ericholscher** [comment]
Nope. Still needs to be fixed :(

**Comment by humitos** [comment]
OK, I copied the patch to that private repository you pointed me. Closing this PR, there is nothing else to do here.

Thanks for your contribution!

**Comment by andrew** [comment]
My first ever python contribution 🎉

**Pull request closed without merging**
