### PR TITLE
Use `--upgrade` flag for user environment `pip install`

### PR DESCRIPTION
**Pull request by wmayner**
Addresses #3027.

I'm not sure if this will cause undesirable side-effects, so more discussion is needed—but I figured I'd make the PR in any case.

### CODE REVIEW

**Comment by wmayner** [comment]
@ericholscher, by the way, I'd be happy to help out triaging tickets—would you grant me the necessary permissions?

**Comment by ericholscher** [comment]
Sure thing. I added you. I know there is a reason we removed the call to `-U` on pip, but I can't remember what it was. I'll do a bit of research and see if I can remember what issue it was causing.

**Comment by wmayner** [comment]
Sounds good. Thanks for the permissions!

**Comment by agjohnson** [comment]
I vaguely recall a problem with pip package caching while forcing upgrades. I'm going to bump up plans to test out feature flagging on projects this week. This is yet another case where we could push out a change on a sample and see if it blows up.

**Comment by wmayner** [comment]
@agjohnson, sounds good! Let me know if I can help.

**Pull request closed without merging**
