### PR TITLE
Sort Version by ascending `verbose_name`

### PR DESCRIPTION
**Pull request by humitos**
This have impact at:

* project's page where all versions are shown
* build a version select combo box (project's page and build page)
* version's tab
* version's tab under Admin

### CODE REVIEW

**Comment by stsewd** [comment]
I think this is on purpose, that way is easy to select the last versions. This is more visible when all the versions are numeric (most of them), so the user doesn't have to scroll/search too much, bc usually the user wants to do an action over the last versions.

**Comment by ericholscher** [comment]
What problem is this addressing? The PR doesn't say _why_ this is a good idea.

**Comment by humitos** [comment]
Well, I found this very unfriendly when reading the list of versions to perform an action on one of them. That's _my_ reason.

captura de pantalla_2018-12-26_18-31-14

captura de pantalla_2018-12-26_18-30-37

Another project that mixes names and numbers,

captura de pantalla_2018-12-26_18-33-15

So, I think that sorting by ascending order will make both cases to "make sense" since it's easier to follow an A to Z order than a Z to A and from 0 to 9 and 9 to 0 won't be a great difference/confusion visually I think.

**Comment by ericholscher** [comment]
I think if we want to sort versions, we should do it smartly. We already have code that takes into account versions when sorting, so we should use this explicitly, instead of trying to do it at the DB level: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/templatetags/projects_tags.py#L13

**Comment by ericholscher** [comment]
Closing this since I don't think it's a good solution. #5151 tracks the issue.

**Pull request closed without merging**
