### PR TITLE
Add advertising details docs

### LINKED ISSUE #3952: tracking on readthedocs.io not mentioned in "Ethical Ads" section of the documentation
## Details

https://docs.readthedocs.io/en/latest/ethical-advertising.html

> - We don’t track you
> - We don’t sell your data
> - We host everything ourselves, no third-party scripts or images

## Expected Result

According to this information, I would assume that there is no tracking on readthedocs.io.

## Actual Result

readthedocs.io always connects to
- google-analytics.com (see also #199 #1221)
- rackcdn.com (with a seemingly unique tracking id)

In addition, readthedocs.io stores a cookie for each subdomain on my PC.

Thus, there seems to be tracking involved. If this is not tracking, it would be nice if you could update the linked article with an explanation or clarify that only clicks are tracked and how (e.g. as in the blog post: https://blog.readthedocs.com/ads-on-read-the-docs/).

### PR DESCRIPTION
**Pull request by davidfischer**
We get a fair amount of inquiries regarding advertising. These usually take the form of one of:

* Request for details around ad targeting
* Questions (occasionally outrage) around "we don't track you" and analytics

The goal of this PR is to cover these as much as possible.

I didn't cover the data retention and data sharing associated with advertising but I want to wait until we have a privacy policy (#2602) in place to do that. It might happen in the privacy policy rather than in these docs.

Fixes #3952 (mostly)

### CODE REVIEW

**Comment by paulmueller** [comment]
Please update *ethical-advertising.rst* as well (see #3952)

> - We don't track you
> - We don't sell your data
> - We host everything ourselves, no third-party scripts or images

To clarify the GA point, maybe change this to something similar to:

- We don't track you. Our current advertising model relies on anonymized Google Analytics data though. For more information, see `:ref:advertising-analytics`.
- We don't sell your data
- We host everything ourselves, no third-party scripts or images

**Comment by davidfischer** [comment]
The key difference above is the addition of the following to the "we don't track you" point:

```Our current advertising model relies on anonymized Google Analytics data though. For more information, see :ref:advertising-analytics```.

Overall I'm -1 on that revision for the following reasons:

- This adds technical details to a document that doesn't really have technical details.
- This puts details of analytics in two places. I don't think we should repeat ourselves.
- This suggests (but doesn't precisely say) that analytics was added for advertising. This is not true. The use of GA on Read the Docs predates advertising on RTD.

Instead I would consider a footnote or possibly a clarifying point in the body that points to the technical details document.

**Comment by paulmueller** [comment]
I am fine with putting this (or similar) information somewhere else in the text. I think it should not be a footnote (footnotes have bad reputation in my opinion, especially when it comes to data privacy).
My idea of putting this information so prominently there was to make absolutely sure that people know what is going on. I agree that the wording might be too technical and the inference that GA would be used for advertising is wrong.

I disagree that GA should not be mentioned in *ethical-advertising.rst* simply because GA is covered in *advertising-analytics* already. Once you motivate ethical ads, you should also be transparent to your users regarding the techniques you use. As far as I understood, GA is used to quantify how many clicks an ad (and other things you as developers might be interested in) gets.

**Comment by davidfischer** [comment]
> I am fine with putting this (or similar) information somewhere else in the text. I think it should not be a footnote (footnotes have bad reputation in my opinion, especially when it comes to data privacy).
My idea of putting this information so prominently there was to make absolutely sure that people know what is going on. I agree that the wording might be too technical and the inference that GA would be used for advertising is wrong.

Your point on footnotes is fair. However, I think having an entire section in the docs is quite prominent.

> I disagree that GA should not be mentioned in ethical-advertising.rst simply because GA is covered in advertising-analytics already. Once you motivate ethical ads, you should also be transparent to your users regarding the techniques you use

I agree with being transparent. That's why we are writing it in the docs. GA is not a secret at Read the Docs. The code is open source and there have been many public issues and pull requests surrounding analytics.

I would classify even the specific analytics implementation ("Google" analytics as opposed to merely "analytics") as an implementation detail. GA can be swapped out but there will always be some sort of analytics even if it is based on log analysis.

> As far as I understood, GA is used to quantify how many clicks an ad (and other things you as developers might be interested in) gets.

This is not the main motivation. We do not rely on Google Analytics for billing advertisers or quantifying clicks. We do fire a GA even for ad clicks but the main reason for that is because GA gives a convenient way to explore that data (do ads perform better on certain themes? certain programming languages? etc.). The primary motivation behind analytics has a paragraph in the new document:

    Advertisers ask us questions that are easily answered with an analytics solution like
    "how many users do you have in Switzerland browsing Python docs?". We need to be able
    to easily get this data. We also use data from GA for some development decisions such
    as what browsers to support (or not) or how much usage a particular page or feature gets.


To propose a solution, how about modifying `ethical-advertising` by changing:

```We have additional documentation on the :doc:`technical details of our advertising <advertising-details>`.```

to 

```We have additional documentation on the :doc:`technical details of our advertising <advertising-details>` including our use of analytics.```

**Comment by paulmueller** [comment]
Ok, I think this a fair solution. Thanks for letting me get involved.

**Comment by davidfischer** [comment]
I made the change based on the proposal above.

**Comment by davidfischer** [comment]
@paulmueller, thank you for getting involved. Taking privacy seriously in advertising is an uphill battle and we are always trying to educate users and take feedback from users in this regard.

**Pull request merged**
