### PR TITLE
Provide guidance for subproject integration

### LINKED ISSUE #2588: Celery is a rather bad subproject example
This has been bothering me for a few years now, but in the [FAQ](http://read-the-docs.readthedocs.io/en/latest/faq.html) it calls out the celery/kombu projects as an example of subprojects. I suppose it's technically true, they are related projects, and they do use the subprojects functionality of RTD. But if you didn't know that kombu existed, you'd never be able to find it from the celery project.

I'd been contemplating using subprojects for awhile now, and my RobotPy project really suffered from the problem of having disconnected documentation sites... so last month I sat down and did some thinking, and I think I came up with a great solution that resulted in a unified set of subprojects that all mostly feel like they're the same site because they share the same sidebar/theme (and because of #1866, the search works across them all too! thanks!). Check it out:

* Main site: http://robotpy.readthedocs.io/
* Subproject 1: http://robotpy.readthedocs.io/projects/wpilib/
* ... and there are others

I also wrote a [blog post](http://www.virtualroadside.com/blog/index.php/2017/01/14/integrated-subproject-sites-on-readthedocs-org/) on how I went about it, that could be useful to link to in the FAQ (or at least borrow the information/technique). 

It would be good for others to have information on how to better use this useful feature. I can PR an edit to the FAQ if you aren't opposed to it -- if there are other/better/bigger examples to cite, that would be fine also.

### PR DESCRIPTION
**Pull request by virtuald**
- Fixes #2588

### CODE REVIEW

**Comment by ericholscher** [comment]
This looks great! Thanks for sending it over. We actually have a `subprojects.rst` in our docs now -- can you move this content over there, and then I'll be happy to merge it :+1:

**Comment by virtuald** [comment]
Should be good to go.

**Comment by agjohnson** [comment]
I just put up #2801 to address some customer questions and remove the celery example, so there are some conflicts with this branch.

There are some really useful tips here 👍 . I feel like `subprojects` is actually the wrong place for this though. Much of this documentation doesn't describe the core functionality of subprojects, and it is in part very particular to your use case.

If we don't already have it, we discussed a section dedicated to user guides or tips/tricks like this -- even if this is just a link to a blog post. I'd be happy to have these examples split up into multiple sections that address the problems more granularly though. This is less helpful to others as a monolith, I feel, and these examples would be helpful to projects that aren't subprojects. Perhaps more granular sections in a user guides section could exist of:

* Detecting the version that RTD is building
* Ensuring the intersphinx version is the same as the project version
* Sharing a sidebar between multiple projects

I held off on review on the actual content, as I figure this should be broken up anyways.

**Comment by virtuald** [comment]
I agree that the individual points could be split up and placed in other locations; however, if one really wants to create a bunch of projects that look/feel integrated, then IMO you need all three points to do it 'right' (at least, given the current features that RTD has available). 

I suppose it would be fine to explain the points and then link to them in a set of bullet points.

**Comment by virtuald** [comment]
Also, for reference @agjohnson, most of this comes from a blog post I wrote: http://www.virtualroadside.com/blog/index.php/2017/01/14/integrated-subproject-sites-on-readthedocs-org/

**Comment by ericholscher** [comment]
Going to close this as I believe most of this information is available in our docs now. Thanks for the contribution @virtuald, and sorry this sat for so long :(

**Pull request closed without merging**
