### PR TITLE
Use autosectionlabel extension

### LINKED ISSUE #4140: Investigate using autosectionlabel in our docs
This Sphinx extension automatically creates references for all sections with the title as the reference:

http://www.sphinx-doc.org/en/stable/ext/autosectionlabel.html

It might be useful to allow us to magically link to section titles in the same fashion in the same document and across documents. 

Refs #3622

### PR DESCRIPTION
**Pull request by stsewd**
I just did a grep to find those links and also to make sure they aren't used in other parts. There are still some links that are used externally (like the yaml file I think) or are out of the scope like the changelog (but I think we can still have those links, going to investigate later).

Closes #4140

### CODE REVIEW

**Comment by humitos** [comment]
OK. I'm interested in making the errors (as changing the title of a section) explicit and communicate them to us. Otherwise, we will end with broken links without knowing it.

**Comment by stsewd** [comment]
@ericholscher I checked that yesterday, we only have one warning about the `_static` directory, also I try activating the `-n` option, I still don't understand it (I remove some refs and everything still works)

http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky

**Comment by ericholscher** [comment]
Huh, interesting.

**Comment by ericholscher** [comment]
@stsewd https://github.com/sphinx-doc/sphinx/issues/3919

**Comment by ericholscher** [comment]
So it looks like our `django.setup()` in the `conf.py` is eating the logging output of Sphinx.

**Comment by ericholscher** [comment]
I actually currently don't see our default Sphinx output in the log for docs locally!

**Comment by ericholscher** [comment]
Even in prod, it's totally swallowing the Sphinx "each page" logging output:

screenshot 2018-05-30 14 45 00

**Comment by ericholscher** [comment]
This discussion moved to https://github.com/rtfd/readthedocs.org/pull/4166

**Pull request merged**
