### PR TITLE
Update all Python dependencies

### PR DESCRIPTION
**Pull request by humitos**
Python requirements updated via `inv packages.upgrade`

### CODE REVIEW

**Comment by ericholscher** [comment]
@humitos I wonder if we should use this bot -- it's pretty handy: https://github.com/writethedocs/www/pull/788

**Comment by humitos** [comment]
@ericholscher looks like a good addition.

I'm reading it and checking its configuration. I need to check how it updates the packages since there are some that we don't have to upgrade automatically because of different reasons.

`pur` handles the `<=` properly for this cases and we are also using `--skip` when calling it.

**Comment by humitos** [comment]
There is an example without too much configuration at #5271 that breaks because of the things that I mentioned. Maybe there is a way to configure it for our needs.

**Comment by humitos** [comment]
I configured it at #5272 and I suppose that it should work as we need.

**Pull request merged**
