### PR TITLE
Pin haystack to latest version that supports django<1.11

### LINKED ISSUE #4005: Incompatible dependencies when installing with pip 10
## Details
Just try a clean local installation following the guide [installing-read-the-docs](http://docs.readthedocs.io/en/latest/install.html#installing-read-the-docs)

## Expected Result
clean installation

## Actual Result

django-haystack 2.8.1 has requirement Django>=1.11, but you'll have django 1.9.13 which is incompatible.

recommonmark 0.4.0 has requirement commonmark<=0.5.4, but you'll have commonmark 0.5.5 which is incompatible.

### PR DESCRIPTION
**Pull request by stsewd**
Ref #4005

### CODE REVIEW

**Comment by stsewd** [comment]
By the way, hystack doesn't have its changelog updated, but the 2.8.0 tag contains this commit https://github.com/django-haystack/django-haystack/commit/514023e01136e9393112252fec7eb3b101932d0b#diff-2eeaed663bd0d25b7e608891384b7298L15

**Comment by stsewd** [comment]
I just saw this doesn't fix completely #4005, with the latest pip version (10), the dependencies are checked in a very strict way, I'm going to do another PR for the other incompatible package since it's more open to discussion.

**Comment by stsewd** [comment]
Ok, my other PR fails to use pip 10 on travis, but we only need to fix recommonmark, so that can be discussed here :)

recommonmark and commonmark were upgraded a long time ago 64ee6f6 cb219e8

BUT recommonmark requires `commonmark>=0.7.3`

https://github.com/rtfd/recommonmark/blob/3238b029b6e19b9cbceb9b85d81304f86b12c012/setup.py#L18

**Comment by stsewd** [comment]
Ok, that wasn't goo, I will revert the change, we only need to update our docs (doing this on other PR).

**Comment by stsewd** [comment]
Seems an issue with `recommonmark`, but seems to be solved https://github.com/rtfd/recommonmark/pull/63, but it's very weird that the version that is on pypi requires an incompatible version :/

**Comment by ericholscher** [comment]
Believe we should be deleting haystack from our dependencies, and code base. It isn't used in production, and just has a few references in our old v1 API.

**Comment by stsewd** [comment]
@ericholscher I'm going to see if I can remove it completely

**Comment by humitos** [comment]
Blocked on #4039. We won't probably need this PR if we completely remove haystack.

**Pull request closed without merging**
