### PR TITLE
Read the Docs footer changes

### PR DESCRIPTION
**Pull request by davidfischer**
This adds a new footer to the site. The footer includes:
- social links
- links to documentation including the getting started guide
- links to information about Read the Docs (team, sponsors, philosophy)
- links regarding sustainability of RTD

**SCREENSHOT**
screen shot 2017-10-10 at 9 57 02 pm

### CODE REVIEW

**Comment by davidfischer** [comment]
I'm taking a look at this. It seems to be an issue with the footer under some error conditions.

**Comment by davidfischer** [comment]
I'm fine making that change. Something like `column-subfooter` and `column-footer` perhaps?

**Comment by davidfischer** [comment]
I'm not in love with `column-footer` mostly because the CSS rule already targets `#footer`. I don't feel that strongly about it though.

**Comment by ericholscher** [comment]
Maybe `column-rtd` and `column-about` -- to match the headings?

**Comment by davidfischer** [comment]
That works. I made those changes.

**Comment by ericholscher** [comment]
This should be merged :+1:

**Pull request closed without merging**
