### PR TITLE
Take preferece of tags over branches when selecting the stable version

### LINKED ISSUE #3268: "stable" appearing to track future release branches
## Details

* Project URL: http://channels.readthedocs.io
* Build URL (if applicable): http://channels.readthedocs.io/en/stable/
* Read the Docs username (if applicable): andrewgodwin

## Expected Result

I expect the "stable" build version to only follow tags, not new branches, as described in http://docs.readthedocs.io/en/latest/versions.html

## Actual Result

The "stable" build says it is following `origin/2.0`, which looks like a reference to a remote Git branch rather than the project's most recent tag, `1.1.8`, which means the "stable" docs have ended up being the in-development version docs.

The "wipe" command does not appear to fix this, and I would like to avoid deleting and remaking the project just to see if it's a bad tag being stored somewhere.

### PR DESCRIPTION
**Pull request by humitos**
I changed a couple of things here.

- add more docstring to some methods
- apply new style rules to modified files
- add a debug package at testing environment

Let me know if you dislike this from this PR and I will remove them.

The interesting commit with the new logic to take a look is https://github.com/rtfd/readthedocs.org/commit/fd0b4062176854a0ac18266be6a92d3113011886

I will add more tests for this new logic.

Closes #3268

### CODE REVIEW

**Comment by humitos** [comment]
I just updated this PR with more logic on the `sync_versions` function and test cases for this.

**Comment by humitos** [comment]
@ericholscher I found another place where this PR is kind of related, can you check my commet at https://github.com/rtfd/readthedocs.org/issues/3268#issuecomment-347965605 and give your opinion?

**Comment by humitos** [comment]
I just added one more commit here to follow what it was suggested in the comment and some tests for these scenarios at: https://github.com/rtfd/readthedocs.org/commit/bcfbca88

Can you please re-review? :)

**Comment by ericholscher** [comment]
Ah yea -- the "version checking" code that is super old and janky :)

**Comment by ericholscher** [comment]
That commit looks good! <3 getting these bugs fixed.

**Comment by willingc** [comment]
Thanks @humitos 👍

**Comment by ericholscher** [comment]
Should be deployed.

**Pull request merged**
