### PR TITLE
Draft policy for claiming existing project names.

### PR DESCRIPTION
**Pull request by jimfulton**
This is prerrt conservative, but it's better than nothing.

### CODE REVIEW

**Comment by ericholscher** [comment]
Might be useful to start with this: https://www.python.org/dev/peps/pep-0541/#reachability -- as it seems much more specific in regards to timing and contact.

**Comment by benji-york** [comment]
PEP-541 looks like a good resource.  In fact, could we simply defer to its definition of "abandoned" to that PEP and have a policy something like "When a project is abandoned (as defined by PEP-541), a request to rename the project by suffixing "-abandoned" (adding incrementally-higher integers if needed for disambiguation) will be granted.

**Comment by ericholscher** [comment]
I think their full policy is quite good and thought out. We should likely adopt the full thing, with some basic changes (eg. `s/downloads/pageviews/`).

**Comment by humitos** [comment]
I think it's a good idea for RTD to adopt that PEP as policy. I think it's pretty clear and will avoid a lot of problems in the future.

**Comment by humitos** [comment]
I'm closing this one because I think we are following this discussion on #3343

**Pull request closed without merging**
