### PR TITLE
Improve error reporting to users

### PR DESCRIPTION
**Pull request by ericholscher**
This lets us hopefully catch both more useful and more errors

### CODE REVIEW

**Comment by agjohnson** [comment]
Pushed up a rebase, but this PR is still being merged into the `celery-` branch. I'll open a new PR

**Comment by agjohnson** [comment]
Moved to #3247

**Comment by ericholscher** [comment]
You can change the base on where the PR goes, FWIW>

**Comment by agjohnson** [comment]
Aha, i didn't realize that was a feature 👍

**Pull request closed without merging**
