### PR TITLE
lowercase domain name in middleware.py

### PR DESCRIPTION
**Pull request by xuchen**
This should fix issue [1366](https://github.com/rtfd/readthedocs.org/issues/1366)

### CODE REVIEW

**Comment by xuchen** [comment]
uh oh, build message:

```
The command "pip install coveralls" failed and exited with 2 during .
```

**Comment by agjohnson** [comment]
This should have some tests as well. Current tests exist at: readthedocs/rtd_tests/tests/test_middleware.py

**Comment by ericholscher** [comment]
:fire: Thanks for the patch! I'll get this deployed today.

**Comment by ericholscher** [comment]
Should be deployed, let me know if this fixes your issue!

**Comment by ericholscher** [comment]
Might take a bit for the cache to clear, but hopefully it will work :)

**Comment by xuchen** [comment]
Hmm.... I still see the Maze Found error after 2 hours. Bummer!!

Is it possible that you see the log message for "http://parsetron.kitt.ai/"? Thanks so much!!

**Comment by ericholscher** [comment]
Yep, found the error:

out:     domain = answer.target.lower().to_unicode()
out: AttributeError: 'Name' object has no attribute 'lower'

On Tue, Jun 23, 2015 at 8:40 PM, xuchen <notifications@github.com> wrote:

> Hmm.... I still see the Maze Found error after 2 hours. Bummer!!
>
> Is it possible that you see the log message for "http://parsetron.kitt.ai/"?
> Thanks so much!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1368#issuecomment-114683395>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by xuchen** [comment]
Ah, the test code missed that.. Really sorry about it!!

**Comment by ericholscher** [comment]
Looks like I fixed it with a change to that code:

out: [23/Jun/2015 19:51:13] DEBUG [core.middleware:65] (Middleware) CNAME
cached: parsetron->parsetron.kitt.ai [parsetron.kitt.ai/en/latest/]
out: [23/Jun/2015 19:51:13] DEBUG [core.middleware:68] (Middleware) CNAME
detetected: parsetron [parsetron.kitt.ai/en/latest/]

:)

On Tue, Jun 23, 2015 at 8:49 PM, Eric Holscher <eric@ericholscher.com>
wrote:

> Yep, found the error:
>
> out:     domain = answer.target.lower().to_unicode()
> out: AttributeError: 'Name' object has no attribute 'lower'
>
> On Tue, Jun 23, 2015 at 8:40 PM, xuchen <notifications@github.com> wrote:
>
>> Hmm.... I still see the Maze Found error after 2 hours. Bummer!!
>>
>> Is it possible that you see the log message for "
>> http://parsetron.kitt.ai/"? Thanks so much!!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rtfd/readthedocs.org/pull/1368#issuecomment-114683395>
>> .
>>
>
>
>
> --
> Eric Holscher
> Maker of the internet residing in Portland, Oregon
> http://ericholscher.com
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by xuchen** [comment]
Hooray!! Thanks so much Eric!!

**Comment by ericholscher** [comment]
Thanks for the patch! :fire:

**Pull request merged**
