### PR TITLE
Remove USE_SETUPTOOLS_LATEST feature flag

### PR DESCRIPTION
**Pull request by humitos**
> This is not tested yet.

We should test that a couple of the projects with this feature in production builds locally when using setuptools==41 and we can deploy it after that I suppose.

### CODE REVIEW

**Comment by stsewd** [comment]
I'm guessing we already have some projects with this flag enabled

**Comment by humitos** [comment]
Actually, we do have ~10k projects with this feature flag.

Currently, _all_ of our projects are building with `setuptools<41`. So, we may want to remove this feature flag from these ~10k (since we know they are building properly now --at least nobody reported anything related) and start from scratch with this: no projects marked to use the latest release. @ericholscher what do you think?

**Comment by ericholscher** [comment]
I think we should remove it -- it was something we were going to test, but I don't think we really ever did anything real with it.

**Comment by humitos** [comment]
I removed the feature flag completely and default to `setuptools==41.0.1`. This is ready to re-review and merge probably.

**Pull request merged**
