### PR TITLE
Docs: Let Theme Choose Pygments Theme

### PR DESCRIPTION
**Pull request by Blendify**
Issue from updating theme to latest.

### CODE REVIEW

**Comment by Blendify** [comment]
Committed without review, Trivial one line patch.

**Comment by davidfischer** [comment]
What is the default if somebody doesn't choose one?

**Comment by humitos** [comment]
This conf file is for the readthedocs documentation. Shouldn't affect people's docs.

**Comment by davidfischer** [comment]
Hah. I got confused. I thought this was a PR on the theme.

**Pull request merged**
