### PR TITLE
Do not list banned projects under /projects/

### PR DESCRIPTION
**Pull request by humitos**
Going to https://readthedocs.org/projects/ you will see many SPAM projects from users that we already banned in our db.

This PR skip showing those projects publicly.

> NOTE: this is not ready to merge yet, since I think it may worth to implement it directly into the `.public` and `.private` method of the `ProjectQuerySetBase` but I want a little of feedback on this first.

### CODE REVIEW

**Comment by ericholscher** [comment]
I guess my larger question is, should we still have project listings? We don't link it, and it doesn't seem to have much value. 

If we're trying to hide spam projects, I think _search_ is likely the most important place to hide them.

**Comment by humitos** [comment]
> I guess my larger question is, should we still have project listings? We don't link it, and it doesn't seem to have much value.

I would completely remove it since it's just a plain list with no value added.

On the other hand, what about my note from the description. Does it worth to that the filter of banned project to _all the queries from that QuerySet_?

**Comment by ericholscher** [comment]
> I would completely remove it since it's just a plain list with no value added.

👍 

> On the other hand, what about my note from the description. Does it worth to that the filter of banned project to all the queries from that QuerySet?

I think it makes sense. There may be unindented issues, but I'm 👍 on trying it. = That would likely help with indexing of search results (and not building the projects will keep the files out of search)

**Comment by ericholscher** [comment]
Merging this, since I think it's useful, and opened #5152 for further work.

**Comment by humitos** [comment]
Hrm... I just merged this PR with the `PR: work in progress` label. It seems that `mergeable` ProBot bot is not installed properly yet.

**Pull request merged**
