### PR TITLE
Remove comments app

### LINKED ISSUE #2879: Unimplemented ModerationActionManger model in comments app
`readthedocs.comments.models.ModerationActionManager` is unimplemented, and contains a single `current_approvals` method which doesn't return anything.  This is probably a cleanup issue.

### PR DESCRIPTION
**Pull request by shreyateeza**
readthedocs.comments.models.ModerationActionManager is unimplemented. This is a cleanup issue.

Closes #2879

### CODE REVIEW

**Comment by Tikam02** [comment]
@shreyateeza  so what's the error causing travis to "All checks have failed". Because there are many issues regarding "Comment" app.

**Comment by shreyateeza** [comment]
@Tikam02 It means that first the rest issues needs to be merged/closed then only travis-ci will succeed. Right?

**Comment by stsewd** [comment]
@shreyateeza There is a import error https://travis-ci.org/rtfd/readthedocs.org/jobs/341953589#L844, you should update/delete some tests.

**Comment by Tikam02** [comment]
yup that's what i was referring import error.

**Comment by ericholscher** [comment]
Would love to see someone take this across the finish line, by deleting the tests too! I would _love_ to merge this :)

**Comment by shreyateeza** [comment]
@ericholscher I am working on this issue!

**Comment by ericholscher** [comment]
@shreyateeza Glad to hear it! Thank you :)

**Comment by humitos** [comment]
@shreyateeza any news on this? We were close to merge it. I'd like to get this done and merged.

Please, if you don't have more time to finish it let us know so someone else can continue your work.

**Comment by shreyateeza** [comment]
@humitos Yes you can assign this issue to someone else.
I am really sorry for not completing this.

**Comment by RichardLitt** [comment]
@shreyateeza No need to apologise at all! We're mostly volunteer run, and we all understand. Contribute what you can whenever you can, if you want. :)

**Comment by humitos** [comment]
I'm closing this one in favor of #3802

**Pull request closed without merging**
