### PR TITLE
bump sphinx to 1.3.4

### PR DESCRIPTION
**Pull request by stevepiercy**
refs #1853, https://github.com/sphinx-doc/sphinx/issues/2189

### CODE REVIEW

**Comment by agjohnson** [comment]
This requires more testing, we'd like to get this bumped soon though.

**Comment by ericholscher** [comment]
I'd like to keep up with Sphinx releases as well. You can always force a particular Sphinx version with your requirements file, if we haven't updated yet.

**Comment by stevepiercy** [comment]
Thanks for the reply. Using the requirements file, it builds with sphinx 1.3.4.

**Comment by agjohnson** [comment]
This PR misses setting the Sphinx version in our virtualenvs as well:
https://github.com/rtfd/readthedocs.org/blob/6fb9ef1c909783eea25824290f7a6fa3aa13cf2d/readthedocs/doc_builder/python_environments.py#L99
https://github.com/rtfd/readthedocs.org/blob/6fb9ef1c909783eea25824290f7a6fa3aa13cf2d/readthedocs/doc_builder/python_environments.py#L189

For whatever reason, this also caused our docs to fail, so there is probably a bit more work to be done here.

**Comment by stevepiercy** [comment]
@agjohnson thanks, updated PR with commit for those items.

**Comment by ericholscher** [comment]
Bigger issue is the docs build failing here. It might be trying to use an old version of docutils, as the error seems to be within docutils.

**Comment by ericholscher** [comment]
Looks like this is an issue with the sphinx http domain.

**Comment by ericholscher** [comment]
I went ahead and fixed the docs with #1935 -- would be good to merge that into this PR, or merge that one first.

**Comment by agjohnson** [comment]
Seems this PR is missing those changes, @stevepiercy

**Comment by stevepiercy** [comment]
@agjohnson oops, somehow I put those changes into origin/origin/patch-2. Fixed, committed, and pushed. Should be good now.

**Comment by agjohnson** [comment]
Thanks @stevepiercy! :+1:

**Pull request merged**
