### PR TITLE
[WIP] Adding docs for hosting with Apache+wsgi

### PR DESCRIPTION
**Pull request by dougthor42**
This PR adds documentation on how to self-host Read the Docs using Apache and WSGI.

Currently a WIP while I work out the kinks and verify all steps.

### CODE REVIEW

**Comment by agjohnson** [comment]
This is probably not the spot for these docs. We don't support Apache httpd and our production stack is not documented in full here either.

**Comment by dougthor42** [comment]
Hmm... OK so what is the preferred method for self-hosting RTD in a production environment?

If you can tell me that, I might be able to investigate the bare minimum requirements and update the docs accordingly.

Simply using `python manage.py runserver` is not sufficient, as per the [Django docs](https://docs.djangoproject.com/en/1.10/intro/tutorial01/):

> Now’s a good time to note: **don’t** use this server in anything resembling a production environment. It’s intended only for use while developing.

**Comment by agjohnson** [comment]
We cover some of this here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

In short, we don't support any other production instances outside our own. This means you won't find our nginx configuration details in our docs either. Having httpd prod setup in our docs would lead to additional confusion, and almost certainly, questions for us on usage that we won't support.

More generally, we assume if you are trying to run a production instance that you know how to maintain Django (including the proper way to run a server), nginx/httpd, Redis, Elastic Search, Postgres, etc in a production environment. We don't have the bandwidth to maintain this information, nor can even offer support on it.

However, I think these docs should exist -- I just personally don't think our official docs are the place.

**Comment by dougthor42** [comment]
Understandable, thanks for the feedback.

I don't have the details for your production environment, so I can't help document that. Sorry!

**Pull request closed without merging**
