### PR TITLE
Upgrade django-pagination to a "maintained" fork

### LINKED ISSUE #3664: Upgrade django-pagination
We are using a fork of the unmaintained `django-pagination` (https://github.com/zyga/django-pagination).

On the other hand, I found that there is another fork that maybe is more maintained at https://github.com/pydanny/dj-pagination

I opened an issue that the 3dparty repository at https://github.com/zyga/django-pagination/issues/42

Ref #2435

### PR DESCRIPTION
**Pull request by humitos**
Closes #3664

The package `django-pagination` got unmaintained, so a fork by Linaro
was created at https://github.com/zyga/django-pagination and got
unmaintained again (https://github.com/zyga/django-pagination/issues/42).

Now, there is another fork at https://github.com/pydanny/dj-pagination)
that contains more compatibility releases. So, I'm upgrading to this one.

### CODE REVIEW

**Comment by ericholscher** [comment]
What method of testing was used here to confirm it doesn't break on the actual site?

**Comment by humitos** [comment]
@ericholscher all the test are passing without problem and I also tested this manually by hitting all the pages where `autopaginate` is used in the template:

* build list
* bookmark list (not used --app to be removed)
* project list

I wasn't able to test it in (I don't have elasticsearch configured)

* search page `/projects/search.html`
* faceted page `/search/faceted_results.html`

Let me know if you consider that it's enough.

**Comment by ericholscher** [comment]
That should be fine. I just wanted to make sure it was tested in a running instance, and not just the unit tests.

**Comment by humitos** [comment]
@ericholscher can we merge this one?

**Comment by humitos** [comment]
@ericholscher can we merge this one?

**Comment by ericholscher** [comment]
👍 -- let's wait til tomorrow, but then merge~!

**Pull request merged**
