### PR TITLE
Make some part of the codebase single source

### PR DESCRIPTION
**Pull request by Carreau**
it does not make RTD run completely on Py3 of course, far from it, but it's a first step.

### CODE REVIEW

**Comment by agjohnson** [comment]
I'm happy to use `six` here as well, if it makes our lives easier.

**Comment by Carreau** [comment]
> I'm happy to use six here as well, if it makes our lives easier.

If there is more invasive changes, I can look into six. Especially if str/string/unicode/byte is involved. 
Most compatibility for Py3 might should not need that. 

I'll use six if I feel the necessary changes would be easier with six.

**Comment by Carreau** [comment]
Should I push more on this branch, want me to actually use six ? Or send smaller changes as separate PRs ?

**Comment by ericholscher** [comment]
I think small PR's like this are best. That way we can get things merged in and they won't rot over time.

**Comment by agjohnson** [comment]
+1 on smaller PRs. Splitting up work between applications, or at least major applications.

I'm fine merging this without six for now -- though there are a lot of API driven calls which will be relying on bytestrings. I'll open a ticket to track implementing `six`.

**Comment by Carreau** [comment]
Thanks ! Sorry I've been busy these days, I'll try to send a few small PR to update for python3 compatibility!

**Pull request merged**
