### PR TITLE
Give more awesome hack for mocking modules

### PR DESCRIPTION
**Pull request by koffie**

### CODE REVIEW

**Comment by agjohnson** [comment]
This seems like a lot of magic to ask users to use, could you elaborate on what this does and what this does differently than the smaller example?

Ideally, I'd rather not have either example in our docs, the user experience of requiring users to add this to their configuration isn't great. It might be really useful like something like this example to exist in our Sphinx extension instead, monkey patching Sphinx's autodoc importing. Our extension could, by some option, enable/disable this behavior.

Our extension is at http://github.com/rtfd/readthedocs-sphinx-ext if you are interested in giving this a try.

**Comment by koffie** [comment]
The thing that this does better then the small example is that it makes something like:

    from a.b.c import something 
    from a.d.e import something_else
    from a.x import whatever

work without the need to add all the submodules of ``a`` explicitly to the list ``MOCK_MODULES``. Which is useful if you have a lot of imports from a fixed module ``a`` going on.

**Comment by koffie** [comment]
It should not be to much work to add some code to the sphinx extension, so that a user can just do something like

    MOCK_MODULES = ['pygtk', 'gtk', 'gobject', 'argparse', 'numpy', 'pandas']
    from readthedocs-sphinx-ext import set_mocked_modules
    set_mocked_modules(MOCK_MODULES)

So some configuration would still be necessary, but at least no copy pasting of code anymore.

**Comment by humitos** [comment]
I also think it's better to add that code to the extension and update the documentation at RTD to reflect this

**Comment by agjohnson** [comment]
Okay, I'll close this then. I'd love to have a more reasonable way to automate this for folks

**Pull request closed without merging**
