### PR TITLE
Tweek css for sphinx_prompt

### PR DESCRIPTION
**Pull request by ovc**
Fix for sphinx_prompt CSS, if you call sphinx_prompt with different prompt sign after previous call.

### CODE REVIEW

**Comment by ovc** [comment]
**If you will use another symbol in a prompt, a function of the prompt will generate another span class with next number, and after all your custom CSS will break the text size.**
 
`cat ./sphinx_prompt_css.css`
`...`
`pre.highlight span.prompt1 {`
` font-size: 12px;`
`line-height: 1.4;`
`}`

`cat ./sphinx_page_with_prompt.rst`

capture1

**The second call of the prompt call break the text (size is different), because of :**

prompt

**Thank you for your review!**

**Comment by stsewd** [comment]
Thanks for the explanation, this looks like only affect to our docs, but looks like a good fix

**Comment by stsewd** [comment]
Also, can you please rebase/merge master? The test failure was already fixed there

**Comment by ovc** [comment]
> Also, can you please rebase/merge master? The test failure was already fixed there

Can you please explain better, what I need to do? Thank you!

**Comment by stsewd** [comment]
@ovc in your branch execute

```
git checkout master
git pull origin
git checkout <your-branch>
git merge master
git push <your-remote> <your-branch>
```

**Comment by ovc** [comment]
@stsewd my changes was already merged in master. I already done another commit. I'm sorry, but I can't understand what I need to do with this trevis error.

**Comment by dojutsu-user** [comment]
@ovc 
It is considered a good practice to create a separate `branch` for each PR.
Since you have made a PR from the `master` branch, you have two options.
1. Pull updated changes in your `master` branch and merge them, add, commit and push.
    You can find the instructions on how to sync a forked repo here : https://help.github.com/en/articles/syncing-a-fork
2. Close this PR and make another PR from a separate branch.
    If you choose this option, make sure that you sync your repo with the latest code updates.

When you are in a separate branch, you can follow the [instructions above](https://github.com/rtfd/readthedocs.org/pull/5281#issuecomment-463681397) to merge `master` branch into your branch

**Comment by ovc** [comment]
@dojutsu-user thank you for your explanation, I merged the changes from upstream/master for now.

**Pull request merged**
