### PR TITLE
Move parser tests from rtd-build repo

### PR DESCRIPTION
**Pull request by stsewd**
I'm not sure if I'm doing this in the proper way, hopefully it's a start.

### CODE REVIEW

**Comment by agjohnson** [comment]
👍 Yeah, so far so good. Is it easier to move this code over in parts like this, or to do all of `readthedocs_build.config` at once? If all at once, I'd say we can make `doc_builder.config` rely on the imported code with this PR as well.

**Comment by stsewd** [comment]
> Is it easier to move this code over in parts like this, or to do all of readthedocs_build.config at once?

I think is fine like this. But I'll attach another little part here (`find.py`)

**Comment by stsewd** [comment]
This is done, I'm leaving `conf.py` and `validation.py` for other PR. After travis is done and a re-review we can merge this :)

**Comment by stsewd** [comment]
I forgot about the unicode literals :disappointed: in the previous commit. Fixed

**Pull request merged**
