### PR TITLE
Upgrade pip to 6.1.1

### PR DESCRIPTION
**Pull request by singingwolfboy**
Follow-on to #1205. Looks like 6.1.1 came out pretty recently.

### CODE REVIEW

**Comment by ericholscher** [comment]
Thanks :)

**Comment by singingwolfboy** [comment]
You're welcome! But -- did you mean to merge this, or close it?

**Comment by singingwolfboy** [comment]
Oh, I see -- this was already done in https://github.com/rtfd/readthedocs.org/commit/463692cec933dcdffba4118db29f71e838fed51e. Never mind!

**Comment by ericholscher** [comment]
Sorry, I saw the travis error and thought it was against the old pip
requirements (just merged a change to the structure) and just committed it
locally.

On Wed, Apr 15, 2015 at 11:44 AM, David Baumgold <notifications@github.com>
wrote:

> You're welcome! But -- did you mean to merge this, or close it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1225#issuecomment-93528947>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Pull request closed without merging**
