### PR TITLE
Document support of .readthedocs.yml

### PR DESCRIPTION
**Pull request by skirpichev**
see rtfd/readthedocs-build#17

### CODE REVIEW

**Comment by skirpichev** [comment]
@ericholscher, @agjohnson, I think this PR was closed by mistake.  Please reconsider and reopen.

**Comment by agjohnson** [comment]
Indeed, i tagged the wrong issue in my commit. Reopened

**Comment by ericholscher** [comment]
Looks good, thanks!

**Comment by ericholscher** [comment]
We'll get this deployed in the next day or so.

**Comment by skirpichev** [comment]
@ericholscher, this still doesn't work, like #2368.  (Locally it's ok.) I believe, the readthedocs-build package wasn't updated.

Could you do a minor release for readthedocs-build, so we can depend on that version instead of using git repo?

**Pull request merged**
