### PR TITLE
Fix git

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by ericholscher** [comment]
On prod:

```
(docs)docs@build03:~/checkouts/readthedocs.org/user_builds/pip/checkouts/latest$ git for-each-ref --format=%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end) %(refname) refs/tags
-bash: syntax error near unexpected token `('

(docs)docs@build03:~/checkouts/readthedocs.org/user_builds/pip/checkouts/latest$ git for-each-ref --format="%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end) %(refname)" refs/tags
fatal: unknown field name: if
```

**Comment by techtonik** [comment]
Maybe upgrade `git`?
```
$ git --version
git version 2.14.1
```

**Comment by safwanrahman** [comment]
Can we use gitpython?
http://gitpython.readthedocs.io/en/stable/

**Comment by ericholscher** [comment]
Yea, our entire VCS backend needs a lot more work and testing.

**Comment by humitos** [comment]
@ericholscher I have the same behaviour that the one you mentioned here in my computer

```
[humitos@julia:poliastro|master]$ git for-each-ref --format=%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end) %(refname) refs/tags
bash: error sintáctico cerca del elemento inesperado `('
[humitos@julia:poliastro|master]$ git version
git version 2.15.1
[humitos@julia:poliastro|master]$ 
```

but it seems that the way we are executing that command from inside the RTD code automatically escapes it _or something_ since I found this issue by running the command with RTD.

**Comment by techtonik** [comment]
@humitos quotes are needed, because ` %(refname)` is a part of format parameter.

**Comment by techtonik** [comment]
@ericholscher so, Edit bug is back? What about upgrading git requirement to 2.x?

**Comment by techtonik** [comment]
Why it is not possible to just update `git` version on server to 2.x?

**Comment by humitos** [comment]
Upgrading the `git` version in the server doesn't fix the issue, does it?

**Comment by techtonik** [comment]
It does. Both commands that were run by @ericholscher on prod fail, but this one (with quotes around format string) fails because of old git version (1.9.1):

    (docs)docs@build03:~/checkouts/readthedocs.org/user_builds/pip/checkouts/latest$ git for-each-ref --format="%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end) %(refname)" refs/tags
    fatal: unknown field name: if

Try it on your system with `git 2.x`:

    git for-each-ref --format="%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end) %(refname)" refs/tags

**Comment by humitos** [comment]
Yes. It works in my system from the terminal but it doesn't work when that
command is ran by the RTD code. It seems there is something wrong when
scapping the quotes

**Comment by techtonik** [comment]
I see. Need to modify tests to actually run `git` over RTD sources. I feel like unit test code is a wrong place for external calls. Is there a better place for it?

**Pull request merged**
