### PR TITLE
Make our SUFFIX default selection py2/3 compatible

### PR DESCRIPTION
**Pull request by humitos**
`dict_keys` can be accessed via indexing, so make a list.

### CODE REVIEW

**Comment by mattpitkin** [comment]
I was just wondering if this fix is going to be released and deployed soon?

**Comment by humitos** [comment]
@mattpitkin yes, it will go out in next deploy. Probably, next week.

**Comment by ericholscher** [comment]
I'm actually likely going to deploy this today.

**Comment by mattpitkin** [comment]
Great, thanks. I think without this fix it must be breaking quite a few Python 3 builds.

**Comment by ericholscher** [comment]
@mattpitkin should be out now if you want to test.

**Comment by mattpitkin** [comment]
Thanks very much. My build gets past the failure that this PR fixed, but then gets the following error:

```
Running Sphinx v1.7.9
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1752, in setup
    app.add_source_suffix('.ipynb', 'jupyter_notebook')
AttributeError: 'Sphinx' object has no attribute 'add_source_suffix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 326, in load_extension
    metadata = mod.setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1755, in setup
    _add_notebook_parser(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1740, in _add_notebook_parser
    source_suffix.append('.ipynb')
AttributeError: 'dict' object has no attribute 'append'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwinpy/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1740, in _add_notebook_parser
    source_suffix.append('.ipynb')
AttributeError: 'dict' object has no attribute 'append'
The full traceback has been saved in /tmp/sphinx-err-7_agp7hk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

However, that seems to be a `nbsphinx` extension error, so I'll look at filling a bug report there.

**Comment by stsewd** [comment]
Yeah, looks like a `nbsphinx` issue

**Pull request merged**
