### PR TITLE
Switch to universal analytics

### PR DESCRIPTION
**Pull request by davidfischer**
This PR is based on #3085. We only need to merge one of them.

Therefore it contains:
- Switches from legacy `ga.js` to new `analytics.js`, solving #1998 
- Switch to Universal Analytics must be done in [`readthedocs-sphinx-ext`](https://github.com/rtfd/readthedocs-sphinx-ext) at the same time, see rtfd/readthedocs-sphinx-ext#29
- Readthedocs pageviews and events are now all prefixed with `rtfd` tracker name, since setting the `trackingId` on a tracker is only allowed on creation (i.e. you can no longer call `_setAccount` in `sphinx.js` and `sponsorship.js`)
- Google Analytics script element has been moved from the bottom of the page to top of `<head>` as per [Googles instructions](https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet)
- Not using the [Alternative async tracking snippet](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet) which should be a bit faster but "can degrade to synchronous loading and execution on IE 9 and older mobile browsers that do not recognise the async script attribute"
- Needs to be tested by someone with access to RTFD Analytics. I've ported the events by referring to the Analytics API docs, but I don't know if they will appear correctly on an Analytics dashboard without changes.

On top of that PR, it also makes sure that pageviews and event tracking work on docs built before this change (using legacy analytics) as well as docs built after this change (using universal analytics).

**VERIFICATION**
I verified that flyout clicks and pageviews were tracked appropriately using the GA debugger extension on both previously built docs as well as docs containing the changes.

screen shot 2018-01-09 at 11 39 55 am

### CODE REVIEW

**Comment by davidfischer** [comment]
I should mention that the bulk of this work was done in the previous PR by @jessetan. My changes were minor.

**Comment by jessetan** [comment]
Is this still preferred over moving the (user) analytics stuff to the theme as suggested in https://github.com/rtfd/sphinx_rtd_theme/pull/411#issuecomment-328533520?

**Comment by davidfischer** [comment]
Thanks for pointing me to that PR. I wasn't aware of the thought process of removing the analytics stuff from extensions (`readthedocs-sphinx-ext`). While I think putting analytics in the themes themselves is fine especially for people using the themes without Read the Docs, for RTD's purposes I think we still need some additions to track some things that regular theme users don't care about (eg. ads, version selector [flyout]).

**Comment by davidfischer** [comment]
I think ideally that themes handle their own analytics however they want to do it. RTD analytics, however, should probably be handled by a script file loaded from media.readthedocs.org.

**Comment by jessetan** [comment]
Alright, so after this PR gets merged, we can proceed with adding user analytics stuff to the theme and reverting the changes to readthedocs-sphinx-ext. The RTD code will then only deal with GA specific to RTD, not page views for the users GA.

**Comment by davidfischer** [comment]
That's my plan. Do you think that'll work for you?

**Pull request merged**
