### PR TITLE
Update donate page with timeless info

### PR DESCRIPTION
**Pull request by ericholscher**
Currently we still have our old fundraiser on the donate page.
We should make this evergreen,
and allow folks to donate at any time.

### CODE REVIEW

**Comment by ericholscher** [comment]
Can't find a good way to make the donate buttons look reasonably good, they float left all the way down.

**Comment by agjohnson** [comment]
@ericholscher i can pull this and patch it up, might be able to resolve with a screenshot though

**Comment by agjohnson** [comment]
Also, instead of removing functionality for the donation drive in the templates, and requiring us to do the work again if we do another drive in the future, perhaps the more correct thing to do is add state to the template that conditionally shows either the 'evergreen' display, or a donation drive with progress bar.

**Comment by ericholscher** [comment]
Yea, I started to add things to the Evergreen section, but can put that back in with conditionals.

**Comment by ericholscher** [comment]
unspecified

Shows the CSS issue.

**Comment by agjohnson** [comment]
Okay, makes sense. The progress bar was removed. Need to reformat things or add some content. I can take a look.

**Comment by ericholscher** [comment]
Another option is to set an amount for the year, and keep ad money that comes in as part of this count to be transparent about all of our income.

**Pull request merged**
