### PR TITLE
Start running our doc builds in nitpicky mode.

### PR DESCRIPTION
**Pull request by ericholscher**
This should catch any missing references and other issues.

It's expected to fail currently, and we should update this branch until
things pass properly.

### CODE REVIEW

**Comment by stsewd** [comment]
There are a lot of errors due to duplicate implicit target name, two or more headers with the same name :/ it's quite impossible to rewrite that, https://github.com/sphinx-doc/sphinx/pull/3388/ looks like making more levels could work

**Comment by ericholscher** [comment]
You can test this locally by running `make clean html SPHINXOPTS="-n"`

**Comment by ericholscher** [comment]
Closing this for now, since we aren't working on it.

**Comment by stsewd** [comment]
We'll need to change the duplicated titles/subtitles to make this work, not sure if we can do that

**Pull request closed without merging**
