### PR TITLE
Removing unused djangome package

### PR DESCRIPTION
**Pull request by gregmuellegger**
@yfdyh000 mentioned in #1157 the translation strings from the oneoffs.html template. However it's not used anymore. So need to have it around and clutter the translation files.

### CODE REVIEW

**Comment by ericholscher** [comment]
I believe the whole djangome app is actually unused. It was a neat idea, but never really got used/documented/etc. I think it's worth looking into it in the future, but for now we can probably just kill it. 

The idea was to have a "smart" URL redirect, do you could go to like ``django.rtfd.org/Queryset`` and it would go to the most popular page hash that has Queryset. It was using Intersphinx inventories to pre-load the shortcuts -- but we never exposed these in the doc UI, and never promoted them.

**Comment by gregmuellegger** [comment]
Oh committing red is so much fun. The latest commits kill `djangome` completely. I therefore also removed the `quick_search` view from the `restapi` endpoint. It was theoretically still in use, but as @ericholscher said we are over it, right?

https://github.com/rtfd/readthedocs.org/commit/b083e00ea29acfa8f6ce17e64997d61bf64cb619 needs some review as this is still using the redis data coming originally from `djangome`. Is the `FileResource.get_anchor` view still in use? It's part of the API v1.

**Comment by gregmuellegger** [comment]
Anyone up for a review on this?

**Comment by agjohnson** [comment]
I'll defer to @ericholscher on this

**Comment by ericholscher** [comment]
Guess we could always bring it back if we wanted to continue support for it. So we can remove it for now -- I think it's a neat idea that never really got off the ground; but that is lots of my ideas, and we definitely don't have the time to make this one fly currently.

**Pull request merged**
