### PR TITLE
Add start and termination to YAML file regex

### LINKED ISSUE #4583: Error when trying to open the yaml file
Triggering builds on this project fails immediately and the error is not well reported to the user.

* https://readthedocs.org/projects/invest/

I checked the logs and it seems there is a problem when trying to read the config file.

```
Aug 29 20:48:03 build03 supervisord: build readthedocs.doc_builder.environments:514[11667]: ERROR (Build) [invest:latest] 'utf-8' codec can't decode byte 0xff in position 24: invalid start byte
Aug 29 20:48:03 build03 supervisord: build Traceback (most recent call last):
Aug 29 20:48:03 build03 supervisord: build   File "/home/docs/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 423, in run_setup
Aug 29 20:48:03 build03 supervisord: build     self.config = load_yaml_config(version=self.version)
Aug 29 20:48:03 build03 supervisord: build   File "/home/docs/checkouts/readthedocs.org/readthedocs/doc_builder/config.py", line 64, in load_yaml_config
Aug 29 20:48:03 build03 supervisord: build     env_config=env_config,
Aug 29 20:48:03 build03 supervisord: build   File "/home/docs/checkouts/readthedocs.org/readthedocs/config/config.py", line 916, in load
Aug 29 20:48:03 build03 supervisord: build     configs = parse(configuration_file.read())
Aug 29 20:48:03 build03 supervisord: build   File "/home/docs/lib/python3.6/codecs.py", line 321, in decode
Aug 29 20:48:03 build03 supervisord: build     (result, consumed) = self._buffer_decode(data, self.errors, final)
Aug 29 20:48:03 build03 supervisord: build UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 24: invalid start byte
Aug 29 20:48:05 build03 supervisord: build readthedocs.doc_builder.environments:624[11667]: ERROR Build failed with unhandled exception: 'utf-8' codec can't decode byte 0xff in position 24: invalid start byte
```

Sentry issue: https://sentry.io/read-the-docs/readthedocs-org/issues/667664442/?query=is:unresolved

It may be related to #4512

### PR DESCRIPTION
**Pull request by humitos**
Otherwise it found files like:

  .hg/store/data/readthedocs.yml.i

Closes #4583

### CODE REVIEW

**Comment by humitos** [comment]
It would be good to have a test for this :)

**Comment by agjohnson** [comment]
Added #4586 in case this is closed before

**Comment by stsewd** [comment]
I'm pushing some tests right now

**Comment by stsewd** [comment]
Tests in https://github.com/rtfd/readthedocs.org/pull/4587

**Pull request merged**
