### PR TITLE
Safe symlink on version deletion

### LINKED ISSUE #3743: Clean deletion of a Version
When a Version is deleted, we are triggering `clear_artifacts` _and_ `symlink_project` but the later is triggered _before_ the object deletion; so, I think if the task is ran before it's effectively deleted the symlink won't be properly synced:

https://github.com/rtfd/readthedocs.org/blob/5472906a067adc60f42556108993255393408410/readthedocs/builds/models.py#L181-L187

To fix this we could chain some Celery task in this order:

1. trigger `clear_artifacts`
1. delete the Version object
1. trigger `symlink_projects`

Take into account that the first and last have to be executed in a broadcast call but the second one should be executed just once since it affects the database.

> This method `Version.delete` is not used in the codebase at all, so I'm not sure if this is a priority. I found that all the Versions are activated/deactivated but not deleted.

Ref: https://github.com/rtfd/readthedocs.org/pull/3649#issuecomment-370915276

### PR DESCRIPTION
**Pull request by stsewd**
Fix #3743

Also, I think we don't use this in code. I thought we were using it when syncing versions, but we call 
https://github.com/rtfd/readthedocs.org/blob/7f2b831ac18ee839535254e9b14e595621ebf653/readthedocs/restapi/utils.py#L172-L172

there, when doing a deletion in that way, django doesn't call the `delete` method.

### CODE REVIEW

**Comment by stsewd** [comment]
Not really sure how to test this one.

And, Investigating more about this, we don't call delete if the version is active, so, if the user deletes the version on the repo and the version is active in rtd, the docs aren't deleted, which is good. If we deactivate the version, it deletes the docs.

That happens here 

https://github.com/rtfd/readthedocs.org/blob/7f2b831ac18ee839535254e9b14e595621ebf653/readthedocs/builds/models.py#L203-L215

So, again, not sure if we need that code.

**Comment by humitos** [comment]
We may want to check the git log to understand why/when that `.delete` code was written.

I suppose that we don't need it since we don't delete versions calling manually `Version.delete`.

**Comment by stsewd** [comment]
This was added here https://github.com/rtfd/readthedocs.org/pull/1686, maybe this can be useful when deleting a version from the admin, not sure.

**Comment by humitos** [comment]
I think it's safe to remove this `delete` method completely. We do have a task called [`remove_orphan_symlinks`](https://github.com/rtfd/readthedocs.org/blob/46b5e0681392230601539257e0ed811060e219c5/readthedocs/projects/tasks.py#L1053) and [`delete_media`](https://github.com/rtfd/readthedocs-ext/blob/627d40855d76057a127b01ce765f404adaf5edaa/readthedocsext/builds/utils.py#L81).

The later is not exactly the same than `clear_artifacts` but similar. Although, `clear_artificts` is being called where it has to be called: when disabling a version or cleaning a version.

**Comment by stsewd** [comment]
OK, turns out we do use this in .com

https://github.com/rtfd/readthedocs-corporate/blob/0738490bb24d88d519db8212bf5cc65690e68073/readthedocsinc/organizations/signals.py#L104-L104

Actually, not sure, I'm not so familiar with that code, so not sure if it's dead code or what, if not, I can revert the latest commit and put the leave the initial fix  :)

**Comment by humitos** [comment]
> OK, turns out we do use this in .com

Good point!

We need to take a look into that before merging this PR and removing the `delete` method. You are right.

**Comment by stsewd** [comment]
@humitos that was added for you actually https://github.com/rtfd/readthedocs-corporate/commit/3b335f359efd4c5045c7b93d0e6f47bf159360ef, I guess we need to keep that code?

**Comment by humitos** [comment]
Yes! I was thinking if we may want to migrate that code to .com, but I think it's correct to use the `.delete` method and keep it where it is.

**Comment by ericholscher** [comment]
It looks like this patch is just a small linting change, is there more to it?

**Pull request merged**
