### PR TITLE
Don’t auto sign folks up with social email.

### PR DESCRIPTION
**Pull request by ericholscher**
We don’t support signing people up with social accounts, so this should be turned off.

### CODE REVIEW

**Comment by jonafato** [comment]
@ericholscher It looks like this might fix #1875, correct? For those of us who've already run into the issue and now cannot connect GitHub accounts, is there a manual fix?

**Comment by agjohnson** [comment]
@jonafato if this is the fix, we'll need to go back, manually correct any user issues, and see if they reproduce the original issue. Once we get it deployed we'll check in with some folks

**Comment by ericholscher** [comment]
I think you should be able to login with your GitHub account and access the
automatically created account through this URL:
https://readthedocs.org/accounts/github/login/?process=login

That should allow you access to the project created.

On Thu, Mar 10, 2016 at 10:10 AM, Anthony <notifications@github.com> wrote:

> @jonafato <https://github.com/jonafato> if this is the fix, we'll need to
> go back, manually correct any user issues, and see if they reproduce the
> original issue. Once we get it deployed we'll check in with some folks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/2052#issuecomment-194981816>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by jonafato** [comment]
I was able to fix my accounts using the steps provided by @dirn. @ericholscher, @agjohnson thanks for the support on this issue.

**Pull request merged**
