### PR TITLE
Fixed build results page on firefox

### LINKED ISSUE #2261: build results page is broken in Firefox
## Details
- Project URL: http://gratipay.readthedocs.io/
- Build URL (if applicable): https://readthedocs.org/projects/gratipay/builds/4082966/
- Read the Docs username (if applicable): whit537
- Environment: Firefox 46 on Mac OS
## Expected Result

Helpful build output (similar to Travis, etc.).
## Actual Result

Cryptic build output:

screen shot 2016-06-08 at 5 32 24 pm

### PR DESCRIPTION
**Pull request by shubheksha**
Fixes #2261

### CODE REVIEW

**Comment by jaraco** [comment]
@agjohnson: My feeling is that the fix, while imperfect, at least makes the site usable on Firefox and Chrome, whereas currently it's only usable on Chrome. Would you consider accepting this fix as a temporary measure, and then we could create a follow-up issue to address the aesthetic issue in Chrome?

**Comment by jaraco** [comment]
Digging into this a little deeper, this `margin: -16px` really feels like a hack for defective rendering in Chrome. Without it, Chrome is adding an ugly amount of whitespace to the span.

**Comment by agjohnson** [comment]
Indeed, see the attached #2261 for more background here

**Comment by agjohnson** [comment]
Closing this PR, there is a new PR open addressing the review changes above.

**Pull request closed without merging**
