### PR TITLE
Shallow git clone

### LINKED ISSUE #1888: Optional use of shallow clone for git repos
It would be great if there was an option to enable shallow clone for repositories. If set, then RtD should use shallow clone (`--depth 1` option of `git clone`) instead of full clone if possible.
This will result in huge disk space saving for projects with large history.

E.g., for one of our projects `/www/readthedocs.org/user_builds/{project}/checkouts/latest` folder takes up to 400 Mb, when cloned with `--depth 1`, it takes up only 12 Mb.

### PR DESCRIPTION
**Pull request by stsewd**
Close #1888 

Tested this locally with a couple of projects, and I didn't find any problems. I also experiment with this outside rtd. The only downside I can see is people using an extension that needs to read the git history. So, this still needs a decision:

1) Merge as it is
2) Add a feature flag and test some projects before
3) Make this a project option, so users can enable/disable it (we can have this on by default)

### CODE REVIEW

**Comment by ericholscher** [comment]
I do wonder if using a higher depth is a bit better. I mentioned back here that travis uses `depth=50`, to better support extensions that read history, etc.

**Comment by stsewd** [comment]
I'm fine with 50 as depth, and skip feature flag, but I wonder if those extensions really exist p: I'll try to search tomorrow.

**Comment by ericholscher** [comment]
I think we should focus on git. It's definitely an 80/20 (or more) situation, so it gives us the most benefit.

**Comment by stsewd** [comment]
I tested this with projects that have a lot of versions, but I'll test this again because I want to be sure that this works with https://github.com/rtfd/readthedocs.org/pull/4433

**Comment by stsewd** [comment]
Tested this with master, still works

**Comment by ericholscher** [comment]
I wonder if we can make this a default depth, but allow it to be user configurable, so that we have an answer if someone needs more history? We can't have this be a YAML option because we don't have the code on disk yet. I think we can ship this with what we have, but I do imagine we'll need a bit more configurability with it over time.

**Comment by humitos** [comment]
> We can't have this be a YAML option because we don't have the code on disk yet. I think we can ship this with what we have, but I do imagine we'll need a bit more configurability with it over time.

To solve this we can:

1. make it a db option, or
1. implement a feature flag (but it's not possible to set by the user, though)

**Comment by stsewd** [comment]
We can make this a web option, something like having all the history or just 50 commits

**Comment by humitos** [comment]
Considering that we are using shallow clone now, shouldn't we use also `--shallow-submodules`?

>        --depth <depth>
>           Create a shallow clone with a history truncated to the specified number of commits. Implies --single-branch unless --no-single-branch is given to fetch the histories near the
>           tips of all branches. If you want to clone submodules shallowly, also pass --shallow-submodules.

**Comment by stsewd** [comment]
That only works when we are cloning the repo and the submodules at the same time, but we don't do that anymore. As the submodules update is separated, I found that we need to update the subdmodules' config to archive this  https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules but that looks a little hacky, not sure

**Pull request merged**
