### PR TITLE
search: index project tags

### PR DESCRIPTION
**Pull request by xrmx**
We have everything in place to index tags but we are not doing it. Do that and make them searchable from the ui. If the change is sound i'll add proper tests.

### CODE REVIEW

**Comment by humitos** [comment]
I'm linking this PR here since it could be interesting for you: https://github.com/rtfd/readthedocs.org/pull/3373

Eric has been working on an upgrade of elasticsearch some time ago but he ran out of time and wasn't able to finish it yet.

**Comment by ericholscher** [comment]
Yea, there is a lot of background around ES with why we're not searching tags. Did you confirm that this works properly in a production instance @xrmx?

**Comment by xrmx** [comment]
@ericholscher i've tested this on my local installation with elastic search 1.5.2 from their docker image. I'll add some tests next week.

**Comment by xrmx** [comment]
So i've taken a look at adding tests but I don't find any elastic search related tests :) I'll take a look at https://github.com/vrcmarcos/elasticmock and see if i can come up with something

**Comment by xrmx** [comment]
Looks like I'm not able to mock Elasticsearch client :| Anyway updated the PR to index by tag slugs and not names.

**Comment by ericholscher** [comment]
Going to close this. We can address the issue of supporting tags or not in #4267 -- but if we want to support it, this work should go into our GSOC search upgrades.

**Pull request closed without merging**
