### PR TITLE
Update mkdocs to the latest

### LINKED ISSUE #3991: edit_uri misbehaving when using mkdocs as rendering engine
## Details

* Read the Docs project URL: https://readthedocs.org/projects/radical-documentation/
* Build URL (if applicable): —
* Read the Docs username (if applicable): mauroservienti 

## Actual Result

I'm trying to setup documentation for our OSS project using Read The Docs, that is much much faster compared to what we're using now. We need to have the `Edit on GitHub` button on every page linking directly to the markdown file in our documentation repo.

I've configured our [`mkdocs.yml`](https://github.com/RadicalFx/documentation/blob/read-the-docs/mkdocs.yml) following the documentation. However regardless of whatever configuration I use it seems that the `edit_uri` setting is always ignored, and the [rendered documentation](http://radical-documentation.readthedocs.io/en/read-the-docs/) `Edit on GitHub` button links to the repo and not to the markdown document.

It seems to me that the problem lies here: https://github.com/rtfd/sphinx_rtd_theme/blob/7cd846b4fdd0e971f2c409ad9a2af24070b7b111/sphinx_rtd_theme/breadcrumbs.html#L40-L46

In which case it's a template issue. Unfortunately I have no idea how the engine works. Looking at the linked code above it seems that the logic is:

* if there is a `github_url` defined directly use that
* otherwise build one (this is what I expect to happen)

The problem with the above code lies in the `display_github` variable that is true only if `github_url` is defined, in with case it means that the if/else will always evaluate to true rendering only the `github_url`, without the full path to the document.

### PR DESCRIPTION
**Pull request by davidfischer**
This does a few smaller changes to mkdocs:

* Updates mkdocs to the latest version 0.17.3
* `cat mkdocs.yml` so it appears in the build logs like `conf.py`. This should make issues with MkDocs easier to debug.

In the 0.17.0 version of MkDocs, there were some [changes to how themes are configured](http://www.mkdocs.org/about/release-notes/#theme-customization-1164). Essentially previously, there was a `theme` setting and a `theme_dir` setting in the `mkdocs.yml`. Now there is a `theme` setting which is a dict with `name`, `custom_dir`, and other settings. We need to support both of these in the event they are building with an older version of mkdocs by pinning it in their requirements.

Should fix #3991.

### CODE REVIEW

**Comment by agjohnson** [comment]
What's the status of mkdocs search on RTD with a modern version?

**Comment by davidfischer** [comment]
I don't know exactly. Was it not working before?

MkDocs (the project) is built with a recent version and here are the search results: http://mkdocs.readthedocs.io/en/stable/search.html?q=something

**Comment by PowerKiKi** [comment]
Search was indeed not working and a [workaround was to inject javascript](https://github.com/rtfd/readthedocs.org/issues/1487#issuecomment-323290547). For the record, the workaround was also implemented in https://github.com/PHPOffice/PhpSpreadsheet/commit/5df66809bcfbea35fcda1513c577470da1b4dbc9. And PhpSpreadsheet also suffers from the broken edit link in the header (#3991). If this PR can solve both issues, that would be awesome.

**Comment by stsewd** [comment]
Maybe this is solved here? (or maybe to consider) https://github.com/rtfd/readthedocs.org/issues/3174

**Comment by ericholscher** [comment]
@stsewd did you test your other PR with this version of mkdocs to confirm? I think we can probably merge this, but might have some support fallout from stuff we weren't doing in a smart way. This is just the default though, so users might already have upgraded.

**Comment by stsewd** [comment]
I was following the latest docs from mkdocs so I think shouldn't be a problem. I no quite understand the rest of your comment. After this is merged, I can rebase and overlap with the other feature, also add more tests for mkdocs there :)

**Comment by ericholscher** [comment]
Great, let's go ahead and ship it then :)

**Pull request merged**
