### PR TITLE
Clarify 'more info' link in admin settings page

### LINKED ISSUE #5175: 'More info' link in admin settings goes to unexpected location
## Details

In Admin->Settings, section 'Documentation type' there is a link titled 'More info'  next to a dropdown menu allowing selection of 'Sphinx Html', 'Mkdocs (Markdown)', 'Sphinx Htmldir' or 'Sphinx 
Single Page HTML'.

## Expected Result

I expected this to link a page containing information about the possible choices from the menu.

## Actual Result

The link is to the `sphinx.builders.html.DirectoyHTMLBuilder` class (http://www.sphinx-doc.org/en/master/usage/builders/#sphinx.builders.html.DirectoryHTMLBuilder). This is unexpected if one is new to read the docs.

### PR DESCRIPTION
**Pull request by EJEP**
Change the 'more info' link in the admin settings page to be more clear that the link is for more information on the sphinx options. Resolves #5175

### CODE REVIEW

**Comment by stsewd** [comment]
Thanks, makes sense for me. We need to add a migration for this change.

**Comment by stsewd** [comment]
You need to run the django makemigrations command

https://docs.djangoproject.com/en/1.11/ref/django-admin/#django-admin-makemigrations

`python manage.py makemigrations --name update-doctype-helptext`

**Comment by stsewd** [comment]
Can you please rebase/merge against master? So mergeable doesn't fail.

**Comment by EJEP** [comment]
I've merged master in

**Comment by ericholscher** [comment]
Thanks!

**Pull request merged**
