### PR TITLE
Added eslint rules

### PR DESCRIPTION
**Pull request by bansalnitish**
This PR adds the following lint rules : 

- semi
- space-unary-ops
- space-before-function-paren
- no-unused-vars

I have removed the errors that were present in the code. Now we get 51 warnings and 0 errors. Except `no-unused-var` all are set to `error`. 

`indent` rule is left to be added. I will make a separate PR just for `indent` as there are large no. of errors (more than 600) associated with adding this rule.

### CODE REVIEW

**Comment by bansalnitish** [comment]
Thanks @davidfischer

**Comment by davidfischer** [comment]
I merged master into this branch and may have created a minor disaster in the commit stream. However, I believe this is merge ready otherwise.

**Comment by davidfischer** [comment]
Actually I may have butchered this. I'm going to see if I can fix it.

**Comment by davidfischer** [comment]
I had to rebase this but I believe we are now ready.

**Comment by davidfischer** [comment]
Thank you very much for the contribution! This is fantastic. :sparkles:

**Comment by bansalnitish** [comment]
Thank you @davidfischer! I am more than happy to contribute :smile:

**Pull request merged**
