### PR TITLE
Move CDN code to external abstraction

### PR DESCRIPTION
**Pull request by agjohnson**
This adds a signal for listening as an external application, purging can be
performed on a project basis there.

### CODE REVIEW

**Comment by ericholscher** [comment]
This should remove the CDN code from inside RTD, as well.

**Comment by agjohnson** [comment]
Forgot that, updated.

**Comment by ericholscher** [comment]
Guessing this is blocked on deployment as well? Looks good otherwise.

**Comment by agjohnson** [comment]
It shouldn't on the community site at least, as there aren't any cdn users configured

**Comment by ericholscher** [comment]
Ah, True.

**Comment by ericholscher** [comment]
:+1: on merging re: conversation above.

**Comment by berkerpeksag** [comment]
It seems like the `'maxcdn'` entries in `tox.ini` and `requirements/deploy.txt` are not needed.

**Comment by agjohnson** [comment]
Need to get back to this and rebase, will need to double check that the pieces we need are in the extension + operations provisioning

**Comment by agjohnson** [comment]
This is now unblocked and should be cleaned up.

**Comment by ericholscher** [comment]
@agjohnson anything specifically that needs to be cleaned up? I don't believe we currently have an CDN users, so this would be a good time to get it merged.

**Comment by ericholscher** [comment]
@agjohnson I'd be +1 on merging this now since we don't have any current CDN users, and we can confirm it works on the next setup we do.

**Comment by humitos** [comment]
@agjohnson is there anything else we need to do here?

It seems that we remove the `purge` function and now it's triggering a signal, but the signal is not connected --so, the old `purge` function / code is not being executed.

**Pull request merged**
