### PR TITLE
Make slug field a valid DNS label

### LINKED ISSUE #2600: Project slug names that are not valid DNS names are not caught on project creation
A sufficiently long enough project name will still be linked from RTD, but the DNS lookup will fail viewing these docs. We should be double checking for slugs that would be 63 characters or more and failing validation.

### PR DESCRIPTION
**Pull request by stsewd**
This PR closes #2600 

Currently rtd serve the docs with the slug of the project as a subdomain, the [spec](https://en.wikipedia.org/wiki/Domain_Name_System#Domain_name_syntax) says that a DNS label can contain up to 63 characters.

I don't know if there is valid project with a slug of this length on rtd.org.

- What action should be taken on this?
- If someone exports a project with a very long name (or put that name on purpose), what slug name should be generated? The slugify function must truncated this names?

### CODE REVIEW

**Comment by stsewd** [comment]
@agjohnson I think is better to let the user choose the slug (see related issue #1440). Maybe changing the slug is a little further, but choosing my own slug in the project creation seems reasonable to me. This will allow the users to put an abbreviation (like rtd instead of read-the-docs) and not get a surprise with a strange slug (like very-long-project-abc for Verry long project), unreal case anyway, I don't think that a project like that is a _real project_ (+64 characters), probably spam.

**Comment by ericholscher** [comment]
I've audited all the existing projects which have good builds, and they are _all_ spam. So I think we're probably safe to just ship this after rebasing the migration.

**Comment by stsewd** [comment]
I have updated the migration and added a data migration, it works locally. But it will explode if there is a collision between slugs. So, maybe we want to implement the slugify thing first?

**Comment by ericholscher** [comment]
I think we're all good:

```
In [5]: Project.objects.annotate(text_len=Length('slug')).filter(text_len__gt=65).count()
Out[5]: 0
```

**Comment by ericholscher** [comment]
Ah yea, I just tested this locally, and it blows up with a DB 500, so we should probably handle this in validation.

**Comment by ericholscher** [comment]
Actually, we should probably just shorten the `name` param to 65 also, which should solve this.

**Comment by ericholscher** [comment]
https://github.com/rtfd/readthedocs.org/pull/4856

**Pull request merged**
