### PR TITLE
Permanent redirect feature added

### LINKED ISSUE #5104: Permanent redirects
## Details

* Read the Docs project URL: https://nodemcu.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

The exact redirect configured as `/en/latest/en/$rest -> /en/latest/` should redirect from https://nodemcu.readthedocs.io/en/latest/en/sdcard/ to https://nodemcu.readthedocs.io/en/latest/sdcard/ using HTTP 301 or 308.

## Actual Result

HTTP 302, temporary redirect (ignore the discussion whether to use HTTP 302 or 303 or 307 for temporary redirects for now). I would assume that users rewriting URLs in the RTD context mean to do that with "permanent redirect" in mind.

### PR DESCRIPTION
**Pull request by saadmk11**
closes #5104

### CODE REVIEW

**Comment by humitos** [comment]
I'm requesting for another review from the @rtfd/core team to be sure that this is the first step to support this.

**Comment by davidfischer** [comment]
Should we add a migration to change all the existing 301 redirects to 302?

**Comment by saadmk11** [comment]
@davidfischer this PR has a migration to change all existing 301 redirects to 302

**Comment by davidfischer** [comment]
Ahhh, I missed that part of the migration. I saw that there was one migration and I assumed it was auto-generated. However, I now see that changing the default and setting all the ones in the DB is in one migration. Thanks.

**Comment by w3guy** [comment]
I want to make the redirects and all future redirects in my project 301. I sent an email and no positive response yet.

When can we get the option to to do this ourselves?

**Comment by humitos** [comment]
@w3guy Hi! I sent you an email yesterday with a question and today I made your redirects 301. Please, keep talking over email. There is no need to comment on a closed PR to ask for support 😃  Thanks!

**Pull request merged**
