### PR TITLE
Enable timezone support and set timezone to UTC

### PR DESCRIPTION
**Pull request by davidfischer**
The two primary changes here are:

* Change [`TIME_ZONE`](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-TIME_ZONE) from `America/Chicago` to `UTC`.
* Set [`USE_TZ`](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-USE_TZ) to `True` (the default is `False`).

These are the defaults for **new** projects in Django.

## Links

* [Django's timezone migration guide](https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/#time-zones-migration-guide)

## Notes

Our production database is already timezone aware so I don't believe this will cause issues with the production database. Django's docs [say as much](https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/#postgresql) but it's worth a second look.

    docs=> SELECT last_login, date_joined FROM auth_user WHERE username='xxx';
              last_login           |      date_joined
    -------------------------------+------------------------
     2018-08-18 22:01:47.979033+00 | 2011-12-22 06:02:28+00
    (1 row)

### CODE REVIEW

**Comment by humitos** [comment]
All your changes look correct to me. Although, I'm not 100% sure how to test other things or where we could find issues by changing these settings.

Maybe it's a good moment to upgrade `pytz` to `2018.05` (currenty `2018.04`) together with these changes.

**Comment by davidfischer** [comment]
> Although, I'm not 100% sure how to test other things or where we could find issues by changing these settings.

That's what terrifies me as well.

**Comment by ericholscher** [comment]
Sounds like it should be raising warnings in the console if we have issues, and I don't see any warnings in our tests. I'm guessing the primary issue is that we might end up with some dates in the future when we do the switch or something like that.

**Comment by davidfischer** [comment]
All the warnings that came from executing the test suite we're fixed as part of this PR. I just suspect there might be some not covered by our tests.

Dates in the database should be ok.

**Comment by ericholscher** [comment]
I'm tempted to try and merge this in. If the DB is correct, then I think we'll be alright. Thoughts?

**Comment by davidfischer** [comment]
> I'm tempted to try and merge this in. If the DB is correct, then I think we'll be alright. Thoughts?

Let's aim for next week. I'll get the coverage into shape and re-run the test suite with Django 1.11.

**Comment by 7mobile56** [comment]
取得 Outlook for Android







On Fri, Nov 2, 2018 at 11:47 PM +0800, "David Fischer" <notifications@github.com> wrote:













I'm tempted to try and merge this in. If the DB is correct, then I think we'll be alright. Thoughts?



Let's aim for next week. I'll get the coverage into shape and re-run the test suite with Django 1.11.

**Comment by davidfischer** [comment]
I'm somewhat confused by the coverage results.

- the patch increases the project overall coverage (I’m not sure how) but is rejected because the diff coverage is too low.
- some files I didn’t modify are shown in the coverage report
- I’m not really sure how to get the patch coverage up without writing tests that test other functionality

I think we are ok here.

**Comment by ericholscher** [comment]
🎉

**Pull request merged**
