### PR TITLE
Remove RTD Theme workaround

### PR DESCRIPTION
**Pull request by Blendify**
This should be merged after https://github.com/rtfd/sphinx_rtd_theme/pull/380 and we use a new release of the theme.

### CODE REVIEW

**Comment by ericholscher** [comment]
This needs to exist for old versions of the theme still.

**Comment by ericholscher** [comment]
This could update the comment to mention being for "versions below X" of the theme. We're working on having better data about theme usage, so we can eventually remove it.

**Comment by davidfischer** [comment]
This is good to go. The CI failures don't seem to be related.

**Comment by davidfischer** [comment]
I'll merge this once https://github.com/rtfd/sphinx_rtd_theme/pull/380 is merged.

**Comment by ericholscher** [comment]
It's just a comment, so I think it's safe to merge now :)

**Comment by jessetan** [comment]
Oh yeah ;)
I was looking at the original commit which removed the line altogether

**Pull request merged**
