### PR TITLE
Do not convert to bytes the `refresh_token`

### LINKED ISSUE #2992: Can't sync outdated Bitbucket repositories
For some reason, the refresh token for Bitbucket is failing. Is this a Bitbucket problem? Problem with our detection of expired tokens? I get this locally as well as on the community site. Removing and adding the Bitbucket connection solves the problem at least temporarily.

Traceback:

```
[05/Jul/2017 14:44:13] celery.worker.job:282[33151]: ERROR Task readthedocs.oauth.tasks.SyncRemoteRepositories[86bd1cbd-0c99-44a6-b5d7-9beadb917a7b] raised unexpected: InvalidClientIdError(u'(invalid_request) (invalid_request) Invalid
 refresh_token',)
Traceback (most recent call last):
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/anthony/dev/readthedocs.org/readthedocs/core/utils/tasks/public.py", line 71, in run
    result = self.run_public(*args, **kwargs)
  File "/Users/anthony/dev/readthedocs.org/readthedocs/oauth/tasks.py", line 22, in run_public
    service.sync()
  File "/Users/anthony/dev/readthedocs.org/readthedocs/oauth/services/bitbucket.py", line 38, in sync
    self.sync_repositories()
  File "/Users/anthony/dev/readthedocs.org/readthedocs/oauth/services/bitbucket.py", line 46, in sync_repositories
    'https://bitbucket.org/api/2.0/repositories/?role=member')
  File "/Users/anthony/dev/readthedocs.org/readthedocs/oauth/services/bitbucket.py", line 172, in paginate
    resp = self.get_session().get(url)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/requests/sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 343, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/anthony/.pyenv/versions/rtd-2.7.8/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 325, in raise_from_error
    raise cls(**kwargs)
InvalidClientIdError: (invalid_request) (invalid_request) Invalid refresh_token
```

### LINKED ISSUE #2993: Project import sync UI doesn't update on failure
Something is up with the promise for updating the UI for syncing remote repositories. If the request returns a 500 response, the UI syncing element is still never updated and remains in a waiting state.

Raised with #2992

### PR DESCRIPTION
**Pull request by humitos**
When the body is encoded, a mix of bytes and unicode happens and it
fails at this line

https://github.com/requests/requests-oauthlib/blob/c472e6bf0468f1bd52b70a64e9aac92bee41c491/requests_oauthlib/oauth2_session.py#L285

(Pdb) body
u'grant_type=refresh_token&allow_redirects=True&refresh_token=b%27z9BSRKqf2QD4pcDhqj%27&client_id=CLIENT_ID&client_secret=CLIENT_SECRET'

(note those weird `%27` in the string)

Closes #2993 
Closes #2992

### CODE REVIEW

**Comment by ericholscher** [comment]
Can we add some logging around this to catch failures better in the future?

**Comment by humitos** [comment]
I think we should connect the logs from this module, since it's already logging the `body`: https://github.com/requests/requests-oauthlib/blob/c472e6bf0468f1bd52b70a64e9aac92bee41c491/requests_oauthlib/oauth2_session.py#L287

**Comment by ericholscher** [comment]
I mean something that would catch the exception/error that would presumably happen on invalid refresh token? The full body isn't gonna help us catch errors, just spam logs :)

**Comment by agjohnson** [comment]
Ideally, we should still solve the issue of a failure here not updating the GitHub repos that were successfully returned.

**Comment by humitos** [comment]
> I mean something that would catch the exception/error that would presumably happen on invalid refresh token?

I think I will need more directions here. I mean, I can catch the exception as you say but then?

I updated this PR with the solution that I imagine you want :)

The `self.get_session` is used in a couple of places (sync repos, setup and update webhooks) but in the other cases it seems that the execption is properly handled. So, this is the one that was missing.

> Ideally, we should still solve the issue of a failure here not updating the GitHub repos that were successfully returned.

I need to take a look in deep at this (each sync is ran in a separate celery task or the same?). I suppose that it's the same, otherwise it shouldn't break the other service. If this is the case, I think I solved it by returning `[]` if something fails. Let me know, since I will need to apply the same logic at https://github.com/rtfd/readthedocs.org/blob/f5d3a8aae4a5338b02899e2b9f6ca90df738cd75/readthedocs/oauth/services/github.py#L151-L163 (maybe I can create a comon `paginate` method that handle this and a `_paginate` in each subclass)

**Comment by agjohnson** [comment]
Correct, all providers are synced in the same task. I am confused why catching these exceptions was even needed now though. Most of the calls in the oauth services are themselves wrapped in try catch, and ultimately raise an exception to the user.

That is, we *want* to raise `Exception('You should reconnect your account')`, which would raise the error to the user -- at least in theory. I haven't tested this.

**Comment by humitos** [comment]
I just refactored the code to handle the exception in both services. For that I created a common `paginate` method in the base class and implement two small methods in each of the subclasses.

If something goes wrong, it returns `[]` as results so other services requests are not affected by the one that it's failing.

@agjohnson can you take a look again at this PR?

**Comment by agjohnson** [comment]
This looks great 👍

The abstraction for `paginate` is a lot nicer now. We'll want to watch for more errors here, but I think the error reporting back should be fine here.

**Pull request merged**
