### PR TITLE
Note about admin page in the docs

### LINKED ISSUE #5581: Where is the admin page? Srsly.
The documentation constantly refers to things that must be done on the admin page. There is no discussion of *where* this page might be found. This seems like a serious oversight.

Also, where is the admin page? I've spent over an hour trying to track it down...

### PR DESCRIPTION
**Pull request by saadmk11**
Added the note to `import-guide.rst` as this is the page on the docs admin page is mentioned for the first time.
closes #5581

### CODE REVIEW

**Comment by stsewd** [comment]
I wonder if putting an image would be more explicit? I think we already put some images around some parts. Just an opinion, not sure.

**Comment by saadmk11** [comment]
Yeah I think so too. I'll Update the PR with a image. Lets see how it turns out.

**Comment by saadmk11** [comment]
@stsewd Updated the PR with Admin Panel Image. Have a look.

**Comment by jkhartshorne** [comment]
Might be worth pointing out that merely being part of the consortium than owns the repo in question isn't sufficient. You have to be logged in *as* the consortium. I spent an hour trying to access the admin page until I figured this out.

**Pull request merged**
