### PR TITLE
Remove typekit fonts

### LINKED ISSUE #3939: Consider removing Typekit Fonts
Currently, readthedocs.org uses Adobe Typekit to load some fonts. These fonts are [Inconsolata](https://typekit.com/fonts/inconsolata), a SIL open font licensed monospace font and four versions of [FF Meta](https://typekit.com/fonts/ff-meta), a proprietary font that is also used on the Read the Docs logo.

I know there is some redesign work going on but I think we can get a quick win by swapping these fonts to using a native font stack for a couple reasons.

* Read the Docs won't look different in development (where TypeKit isn't available) vs production
* There are performance improvements from not having to download fonts although they aren't huge on readthedocs.org (they're much larger on the RTD theme). It's ~115kb and can be around 1/3 of a second. If you see the "flash of unstyled text" when loading readthedocs.org, this is why.
* Some users consider Typekit a "tracker" and are concerned about its security and privacy implications. Regardless of your thoughts on that subject, it is 3rd party code we are currently executing on Read the Docs. If we don't use these fonts, we don't need TypeKit.

The biggest downside is that the Read the Docs logo will use a different font than the rest of the site.

I'd be happy to put together a small PR swapping to a native font stack. I believe it will only touch 1 file and be only a few lines. Thoughts?

I detailed some of my thoughts on native font stacks in a ticket on the RTD theme (https://github.com/rtfd/sphinx_rtd_theme/issues/524).

### PR DESCRIPTION
**Pull request by davidfischer**
This replaces the fonts loaded from Typekit with a native font stack.

The code fonts use the same stack as in https://github.com/rtfd/sphinx_rtd_theme/pull/612.
The regular text font uses the same font stack as GitHub.

Fixes #3939

### CODE REVIEW

**Comment by ericholscher** [comment]
Seems like a solid step forward to me. I don't think we need fancy custom fonts enough to require a third party for this. 👍

**Comment by davidfischer** [comment]
@agjohnson, we are discussing dropping Lato on the theme as well. Currently, it is ~1.5MB to download Lato on the theme (https://github.com/rtfd/readthedocs.org/issues/3564). That would be reduced by only around half if we correctly gzipped them or served woff's. That's a lot of performance penalty for a font.

In general I'm +1 on a native font stack vs having a flash of unstyled text and longer load times but I don't feel that strongly.

**Comment by agjohnson** [comment]
I'd be -1 on dropping Lato from our theme. It was originally used because it provided a better default experience for a wider range of non-CJK character sets. Its also an attractive type, which is baked into our theme experience -- i wouldn't want to leave display up to the OS here. I don't have a good solution for reducing load time here besides gzip compression though.

At very least, combining the asset source for docs and dashboard makes sense.

**Comment by davidfischer** [comment]
While I believe that native OS fonts have gotten much better in the last few years with both Apple and Microsoft releasing high quality fonts for their platforms recently with great character support, I'm fine sticking with Lato and I'll rework this PR to use it. It is important to stay on brand. I'll see what can be done from the performance side. Most likely that will mean including the woff files in addition to the ttf.

> At very least, combining the asset source for docs and dashboard makes sense.

I don't think I'm going to worry about this specifically in this PR as that will likely involve theme changes.

**Comment by davidfischer** [comment]
I added Lato. Without subsetting the fonts (removing glyphs we don't need) the total for the regular, italic and bold versions of Lato are a little more than 1MB. Woff files are already compressed and so this can't be improved by gzipping.

Woff files are sufficiently supported I believe where we don't even need to deliver the TTFs at all: https://caniuse.com/#search=woff

**Comment by agjohnson** [comment]
Aye, woff files should be enough by now. I'd say we can grep our logs to see ttf vs woff(2) usage of Lato currently, but our theme doesn't ship woff/woff2 :(

**Comment by agjohnson** [comment]
Changes look fine. I'd say we should be installing through bower for more consistent upgrades, but I think a new theme will replace the need for this anyways.

**Comment by ericholscher** [comment]
🎆

**Comment by davidfischer** [comment]
> Aye, woff files should be enough by now. I'd say we can grep our logs to see ttf vs woff(2) usage of Lato currently, but our theme doesn't ship woff/woff2 :(

This is probably a good change on sphinx_rtd_theme. We can get the improvements in performance without the nginx config changes around font gzipping.

Shipping woff only will mean formally dropping full support for IE8 and before (IE8 users would see a fallback font). There is some discussion of a formal browser support policy in https://github.com/rtfd/sphinx_rtd_theme/issues/525.

**Comment by agjohnson** [comment]
I don't think we want to disallow ttfs, just serve woff with precedence. The addition would just be a woff/woff2 font option in our css font declaration.

**Comment by davidfischer** [comment]
I'm fine with that. It will be around 700kb more per docs build since we will have woffs in addition to TTFs.

**Comment by davidfischer** [comment]
It does look like older browsers also don't support the ttf though: https://caniuse.com/#feat=ttf

**Pull request merged**
