### PR TITLE
Add tests for build json in html feature

### PR DESCRIPTION
**Pull request by stsewd**
The missing tests for https://github.com/rtfd/readthedocs.org/pull/4229

I'll add some comments later.

### CODE REVIEW

**Comment by ericholscher** [comment]
I'm not sure if we really need to test this, as it's a short-lived deployment of a feature flip. We should really be testing the actual logic that is happening during the documentation build to get the JSON out with specific things (like unicode and sphinx domain objects). That is much harder to test though :)

**Comment by stsewd** [comment]
Got it, I don't think we have something like that in rtd, right? (only saw something like this in the rtd-extension repo)

**Comment by ericholscher** [comment]
@stsewd yea, it's mostly tested in the extension, which is fine. I think we're mostly covered at this point, and then as we deploy it more widely, we'll see regressions (maybe not!) and then add tests to cover those cases.

**Comment by stsewd** [comment]
Got it, closing this.

**Pull request closed without merging**
