### PR TITLE
Simplify lock acquire

### PR DESCRIPTION
**Pull request by stsewd**
Currently we are acquiring 3 locks.
We should only have 2 (we can't have only one because of #5672)

Basically I'm removing the locks from `setup_python_env` and `build_docs` to only acquire the lock in a central place (`run_build`)

### CODE REVIEW

**Comment by stsewd** [comment]
I still want to test this more locally before merging :)

**Comment by stsewd** [comment]
Locking is working, this is ready for review.

**Comment by humitos** [comment]
Why not to acquire the lock immediately inside the `run` method of the build task so the whole build process (API query, setup, build docs, etc) is inside the lock?

Otherwise, the `clean_build_task` from #5680 could clean these files while we are performing the `run_setup` step.

**Comment by stsewd** [comment]
That's the trick, the lock needs to be acquired inside the `with self.build_env` context manager. Because the decorator catch the `VersionLocked` error, otherwise the task will not shown as failed and would be retying without showing anything to the user.

**Comment by humitos** [comment]
Yeah, but we can create the `self.build_env` (or `self.setup_env`, it's the same for this) immediately after getting the project, version, build and env vars from the API. That's all what we need to create it and we can use the context manager after that wrapping the rest of the execution. Don't you think?

**Comment by stsewd** [comment]
There are two build environments, that's why we need two locks.

build_env_1 -> lock
build_env_2 -> lock

Nesting isn't possible due how build_env works and expects lock to be inside the build env context manager.

Also, the second build_env depends on the first, which gets the config file to initialize the next build_env with the correct docker image.

**Pull request merged**
