### PR TITLE
Make test fixtures explicit

### PR DESCRIPTION
**Pull request by gregmuellegger**
I have the following goals:

- [x] [1] Remove dependency on `bamboo_boy`
- [x] [2] Remove dependency on `factory`
- [ ] [3] Do not use JSON fixtures in tests

On (1): When I first looked at the test suite, I got really confused on what function the `bamboo_boy` library has. It uses the following names as modules and objects: `bamboo_boy.materials`, `Clump` (a class), `canopy` etc.. All of the names are not related to anything I would expect in a test. They are not speaking about what they are actually doing which is really bad pattern and will confuse anyone who doesn't know the library. Also there is no PyPI release of bamboo boy.

On (2): The factory classes in the tests are encapsulating the creation of objects. That is good pattern in general. But in tests it's moving the logic on how objects are created away from the actual test case. That means you need to know about more places in the tests to fully understand the environment in which a test is run. IMO test should always be run in a fully controlled environment where all the influencing parts are visible at a glance (e.g. the data is explicitly created either in the test itself or in the `setUp` method). So the problem I have with `factory` is not the library itself but that we define the creation of test data to far away from the actual test case.

On (3): This reasoning for not depending on JSON fixtures for test data is similiar to what (2) is describing. It's hard to grasp what the JSON fixtures contain which makes the test data environment less obvious. Another big drawback of the JSON fixtures are that they are reused between many tests. If you want to add new tests which test additional edge cases and are adding data to the JSON fixtures, you are likely to break other existing tests because they assume a fixed set of data from the fixture. Also maintaining JSON fixtures when the database schema changes is time consuming and boring.

I would like to resolve all these issues by moving the test fixture creation away from bamboo boy and JSON fixtures over to using `django_dynamic_fixture`.

After all the chosen library is a matter of taste, so I'm open for other suggestions (even `factory` might be a valid choice), but the bad patterns I described here are not a matter of taste. We should get rid of them as they have already bitten me while getting into the project and make the test suite harder to approach for new developers then necessary.

(The code in this PR is not complete yet, as I wanted to discuss this first before investing too much time on it)

### CODE REVIEW

**Comment by ericholscher** [comment]
:+1: on the general cleanup. We've reused a lot of the JSON fixtures instead of solving this problem, so it makes sense. It definitely feels brittle; in fact I hit that last week as well.

I don't have a lot of opinion on what library to use.

**Comment by ericholscher** [comment]
Went ahead and used django-dynamic-fixtures in #1523 and enjoyed it. It was quite easy.

**Comment by gregmuellegger** [comment]
The factory and bamboo libraries are no longer required. I started doing the refactor to not depend on JSON fixtures. But that's quite a time consuming task. I think it's ok for now that they still depend on the test_data.json. We can convert them as we go and avoid using the fixtures when creating new tests.

**Comment by ericholscher** [comment]
:+1: Lost 17 lines of test code as well :)

**Pull request merged**
