### PR TITLE
Correct whitespace issues

### PR DESCRIPTION
**Pull request by sils1297**
This commit was generated using
`coala --files=\*\*/\*.py --bears=SpaceConsistencyBear -S use_spaces=True` and strips trailing whitespaces and replaces tabs with four spaces.

The coala tool can be retrieved from
https://github.com/coala-analyzer/coala/

### CODE REVIEW

**Comment by gregmuellegger** [comment]
:+1: Looks good to me. It only touches insignificant whitespace.

**Comment by d0ugal** [comment]
Agreed and it also converts a few tabs to spaces. That sold it to me!

**Comment by gregmuellegger** [comment]
So it's in! Thanks @sils1297  for taking the time to create that patch.

**Comment by sils1297** [comment]
No problem!

2015-06-11 15:13 GMT+02:00 Gregor Müllegger <notifications@github.com>:

**Comment by sils1297** [comment]
By the way you can use coala easily to ensure no whitespace problems are introduced via travis.

**Pull request merged**
