### PR TITLE
Move dynamic-fixture to testing requirements

### PR DESCRIPTION
**Pull request by stsewd**
As far as I know, this is only used for testing, also I did a grep on the project and only found imports on test files.

### CODE REVIEW

**Comment by humitos** [comment]
@stsewd can you check the errors on travis, please?

**Comment by stsewd** [comment]
@humitos I didn't run the tests for the linter on my local instance, I'm going to see why the package is required by the linter.

**Comment by stsewd** [comment]
OK, I found the issue, I'm solving it on https://github.com/rtfd/common/pull/6

**Comment by ericholscher** [comment]
Think this should be unblocked now.

**Comment by stsewd** [comment]
I updated the submodule, this is ready :)

**Comment by ericholscher** [comment]
👍

**Pull request merged**
