### PR TITLE
Porting the codebase  to Django 1.8

### PR DESCRIPTION
**Pull request by gregmuellegger**
So here we are, we should switch to a supported Django version. The tests pass and the `runserver` works. However we should test more extensively before we merge this into `master` or deploy anything to the server. Here are some notes.

# Release Notes

- Updated Django from `1.6.11` to `1.8.3`.
- Removed South and ported the South migrations to Django's migration framework.
- Updated django-celery from `3.0.23` to `3.1.26` as django-celery 3.0.x does not support Django 1.8.
- Updated Celery from `3.0.24` to `3.1.18` because we had to update django-celery. We need to test this extensively and might need to think about using the new Celery API directly and dropping django-celery. See release notes: http://docs.celeryproject.org/en/latest/whatsnew-3.1.html
- Updated tastypie from `0.11.1` to current master (commit `1e1aff3dd4dcd21669e9c68bd7681253b286b856`) as 0.11.x is not compatible with Django 1.8. No suprises expected but we should ask for a proper release, see release notes: https://github.com/django-tastypie/django-tastypie/blob/master/docs/release_notes/v0.12.0.rst
- Updated django-oauth from `0.16.1` to `0.21.0`. No suprises expected, see release notes [in the docs](https://django-allauth.readthedocs.org/en/latest/changelog.html) and [finer grained in the repo](https://github.com/pennersr/django-allauth/blob/9123223f167959e4e5c4074408db068f725559d1/ChangeLog#L1-169)
- Updated django-guardian from `1.2.0` to `1.3.0` to gain Django 1.8 support. No suprises expected, see release notes: https://github.com/lukaszb/django-guardian/blob/devel/CHANGES
- Using `django-formtools` instead of removed `django.contrib.formtools` now. Based on the Django release notes, these modules are the same except of the package name.
- Updated pytest-django from `2.6.2` to `2.8.0`. No tests required, but running the testsuite :smile: 
- Updated psycopg2 from 2.4 to 2.4.6 as 2.4.5 is required by Django 1.8. No trouble expected as Django is the layer between us and psycopg2. Also it's only a minor version upgrade. Release notes: http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-4-6
- Added `django.setup()` to `conf.py` to load django properly for doc builds.
- Added migrations for all apps with models in the `readthedocs/` directory

# Backwards Incompatible Changes

- I removed the possibility to switch out the profile model (basically ignoring the `AUTH_PROFILE_MODULE` setting). This was the easiest way to compensate for the removal of `User.get_profile`. Is the settings actively used in any readthedocs installation you know of?

# Deployment Notes

After you have updated the code and installed the new dependencies, you need to run these commands on the server:

```
python manage.py migrate contenttypes
python manage.py migrate projects 0002 --fake
python manage.py migrate --fake-initial
```

Locally I had trouble in a test environment that pip did not update to the specified commit of tastypie. It might be required to use `pip install -U -r requirements/deploy.txt` during deployment.

# Development Update Notes

The readthedocs developers need to execute these commands when switching to this branch (or when this got merged into master):

- **Before updating** please make sure that all migrations are applied:
```
python manage.py syncdb
python manage.py migrate
```

- Update the codebase: `git pull`
- You need to update the requirements with `pip install -r requirements.txt`
- Now you need to fake the initial migrations:
```
python manage.py migrate contenttypes
python manage.py migrate projects 0002 --fake
python manage.py migrate --fake-initial
```

You are ready to go now.

btw, shall we document that somehow in the documentation? Or is a one-time post to the mailinglist sufficient?

# Open Tasks

- [x] Review and update docs about installation process
- [x] Extensive tests in production-like environment, using Postgres as DB
- [x] Extensive tests in production-like environment, using Celery with Redis

### CODE REVIEW

**Comment by ericholscher** [comment]
:fireworks: This is great progress already.

**Comment by ericholscher** [comment]
I believe nobody is using custom User models. I think that change makes sense, at least for now.

**Comment by gregmuellegger** [comment]
**A few updates:**
* Updated psycopg2 from 2.4 to 2.4.6 as 2.4.5 is required by Django 1.8. No trouble expected as Django is the layer between us and psycopg2. Also it's only a minor version upgrade. Release notes: http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-4-6
* Added migrations for all apps with models in the `readthedocs/` directory
* Adjusted the installation guide to say `./manage.py migrate` instead of `./manage.py syncdb`
* Tests using Celery and Redis with the updated libraries were successfull. Docs have been built

**Notes for delpoyment:**
Locally I had trouble in a test environment that pip did not update to the specified commit of tastypie. Are there any options to force the update on a normal `pip install -r requirements/deploy.txt`?

I have integrated the above comments into the ticket description.
Currently the Travis builds are failing. But I have no idea why. It works locally for me with a fresh clone and virtualenv. Does anyone know a good way to debug issues that only occur on Travis?

**From my side the PR is ready to be reviewed and tested by someone**

**Comment by ericholscher** [comment]
I believe you want `pip install -U -r reqs` -- the normal way will update
versions, but not hashed checkouts, I believe.

This is great news. This is on my plate to get tested.

On Thu, Jul 16, 2015 at 7:02 AM, Gregor Müllegger <notifications@github.com>
wrote:

> *A few updates:*
>
>    - Updated psycopg2 from 2.4 to 2.4.6 as 2.4.5 is required by Django
>    1.8. No trouble expected as Django is the layer between us and psycopg2.
>    Also it's only a minor version upgrade. Release notes:
>    http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-4-6
>    - Added migrations for all apps with models in the readthedocs/
>    directory
>    - Adjusted the installation guide to say ./manage.py migrate instead
>    of ./manage.py syncdb
>    - Tests using Celery and Redis with the updated libraries were
>    successfull. Docs have been built
>
> *Notes for delpoyment:*
> Locally I had trouble in a test environment that pip did not update to the
> specified commit of tastypie. Are there any options to force the update on
> a normal pip install -r requirements/deploy.txt?
>
> I have integrated the above comments into the ticket description.
> Currently the Travis builds are failing. But I have no idea why. It works
> locally for me with a fresh clone and virtualenv. Does anyone know a good
> way to debug issues that only occur on Travis?
>
> *From my side the PR is ready to be reviewed and tested by someone*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/pull/1420#issuecomment-121966228>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
Hmm, when running it I am getting:

There is no South database module 'south.db.postgresql_psycopg2' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

**Comment by ericholscher** [comment]
Ah, I actually had to **uninstall** south.

**Comment by ericholscher** [comment]
Got it running and building locally :fireworks:

**Comment by gregmuellegger** [comment]
Ohoh, yes i ran into it as well and forgot to document it. My fault. You
need to uninstall south as some modules are importing it, yielding this
error.

There are no references to south in the codebase left and in my knowledge
all dependencies handle south optionally.
Am 16.07.2015 22:06 schrieb "Eric Holscher" <notifications@github.com>:

**Comment by ericholscher** [comment]
Merging this, with a plan to deploy it in the next couple evenings. We have the `rel` branch now, so we can still cherry-pick emergy deploys, but I don't want this code to rot, and it's blocking some larger cleanup since it also touches a lot of the codebase.

**Comment by ericholscher** [comment]
I added these notes to a changelog here: http://docs.readthedocs.org/en/latest/changelog.html

**Pull request merged**
